### ISSUE TITLE
evaluate codacy

### ISSUE THREAD

**Issue by dbarrosop** [nornir-automation/nornir#150]
Provides both static analysis and coverage. Might be interesting.

**Comment by dbarrosop** [comment]
Alternatively switch to pylint.

**Comment by ktbyers** [comment]
@dbarrosop pylint does find some things that are useful (that are current linters aren't catching) like when you accidentally use a built-in. 

There is a bunch of garbage we in pylint we would have to turn off, but that should be easy.

codacy is new to me, but open to trying it.

**Comment by ogenstad** [comment]
Aren't both of those a thing that just gives you a grade? Can't we enable both of them and see what they say and then choose based on that?

**Comment by dbarrosop** [comment]
> pylint does find some things that are useful (that are current linters aren't catching) like when you accidentally use a built-in.

I agree, I realized thanks to pylint I have been making the mistake of using `vars` as an argument for various functions :(

> Aren't both of those a thing that just gives you a grade? Can't we enable both of them and see what they say and then choose based on that?

codacy basically uses pylint under the hoods so I'd suggest toying with pylint first and then we decide about codacy.
