### ISSUE TITLE
Adapt writing-a-custom-inventory howto to use InitNornir

### ISSUE THREAD

**Issue by dbarrosop** [nornir-automation/nornir#151]
Mostly to avoid confusing users.

https://github.com/nornir-automation/nornir/blob/develop/docs/howto/writing_a_custom_inventory.rst#writing-a-custom-inventory

**Comment by ogenstad** [comment]
What needed to be done here?

**Comment by dbarrosop** [comment]
The example uses:

```
inv = MyInventory()
nornir = Nornir(inventory=inv)
```

So it'd be nice to use `InitNornir` instead there as that's what most people uses anyway.

**Comment by dbarrosop** [comment]
Also, "group" -> "groups".
