### ISSUE TITLE
Introduce type hints PEP484 and integrate mypy into CI/CD

### ISSUE THREAD

**Issue by dmfigol** [nornir-automation/nornir#163]
This issue was opened to discuss if **nornir** should introduce type checks and mypy.

[Mypy](https://mypy.readthedocs.io/en/latest/) is a static type checker for Python 2 and 3.
It is quite smart and can infer a lot of types based on the code and type hinting which was introduced with [PEP 484](https://www.python.org/dev/peps/pep-0484])
Prior to Python 3.6 type hints were specified using comments: `  # type: <type>`, but Python 3.6 introduced new type hinting using:
`var: <type> = <value>`
While some perceive it as ugly, it really helps (at least in my opinion):
- easier to document types there instead of docstrings, which can easily become outdated (just to clarify, I am not saying to remove docstrings, just types from them)
- easier to understand the code with types
- static type checker like mypy can catch some bugs early
- with more adoption, library maintainers will be pushed to migrate to it or provide stub files describing types so that application using the library can leverage those types

I am definitely not a mypy expert, but I was helping [certbot](https://github.com/certbot/certbot) (medium codebase, around 35k LoC) to migrate to mypy during PyCon sprints. We caught a dozen of small bugs and found places with weird code that definitely require refactoring.

The strategy was:
1) Add mypy with weak checks
2) Fix all found problems
3) Add mypy to CI/CD
4) Switch to stronger type checking settings one at a time
5) Repeat 2-4

As a point of reference we used [this document](https://blog.zulip.org/2016/10/13/static-types-in-python-oh-mypy/) written by Zulip team who successfully migrated to mypy for even larger codebase.
Good presentation to understand type hints and how to do it in real-world: [Carl Meyer - Type-checked Python in the real world - PyCon 2018](https://www.youtube.com/watch?v=pMgmKJyWKn8)

**Comment by dbarrosop** [comment]
I am personally in favor of strongly typed languages so I am completely fine with this. The drawback is killing support for py3.5 which I wouldn't mind anyway so if @ktbyers and @ogenstad agree as well I say we do it.

**Comment by ktbyers** [comment]
I think we previously agreed we were only going to support Python3.6 or greater.

@dmfigol Do you have much sense how much work is required to add in this support? I have only looked at it in a cursory way.

**Comment by dmfigol** [comment]
Not a lot, I'd guess 5-8 hours to migrate the whole codebase. 
It will also take some time getting used to it. At the beginning it just feels weird.
Basic types are simple, but there are a lot of knobs for more complex types.

**Comment by ogenstad** [comment]
A lot of environments I work in are quite old, sometimes it feels like I'm still running Yggdrasil Linux. But I would rather work on something fun instead of spending the time to support older environments. If we should drop Python 3.3 -> 3.5 I think that should happen soon so that people are aware of the fact that Nornir is 3.6 only (and 3.7 :) ).

**Comment by dbarrosop** [comment]
I suggest the following:
1. Try to find a story for async (either as an alternative mode for the current multithreading model or as a replacement)
2. Play with mypy and evaluate the benefits
3. Evaluate which type of user may need help to make nornir work in older environments and how we can do that (docker? vagrant? other? we can experiment with @ogenstad ;))

I completely agree we should do this but I think we shouldn't rush it and make sure we have a good story before killing py3.3-3.5 support.

**Comment by ktbyers** [comment]
Python 3.3 is EOL...so it is only 3.4 and 3.5 that even need considered (for older releases).

I am pretty strongly against using asyncio as a replacement for threads. It adds a lot of complexity and in the networking context (where we are constantly waiting for IO), and I don't think the complexity is worth it. Note, I am sure there are contexts where async makes sense, I doubt this is one of them though. 

Note here I am talking about single-threaded, asynchronous code with an event-loop.

I think we should look at concurrent futures though for reimplementing the thread-pool.

On mypy, I agree that we should only be evaluating it. I don't have enough context on the work involved in using it or the benefits we get from it.

**Comment by ogenstad** [comment]
I think the main thing with asyncio would be that Napalm and Nornir would need to be rewritten in order to be usable as plugins. Would perhaps be easiest to provide it as an alternative. Regarding 3.3 I don't think it's an issue if it works on 3.4 I think it will mostly work on 3.3. 

Nornir (or Brigade) started out using concurrent futures, it was very slow with larger inventories though. But we could, of course, revisit that part.

>Evaluate which type of user may need help to make nornir work in older environments and how we can do that (docker? vagrant? other? we can experiment with @ogenstad ;))

I used Docker as a workaround for that. I think 3.5 is still the latest version that Ubuntu uses. So by default 3.6 will probably mean fewer users. Might avoid certain types of questions though. :)

**Comment by dmfigol** [comment]
Yes, to support asyncio, a bunch of code should be rewritten. That's why I was asking if it was considered at the beginning.
However, there is still a possibility to support it, at least in theory. The runner will need to be different, for example `.arun()` instead of `.run()` and tasks should be obviously async. This runner will call `run_until_complete` with Futures created from async functions. Once I have some time, I will try to implement it in a new branch. If it works, imagine the scalability numbers you can get, especially considering that it is possible to run asyncio in threads.

@ogenstad I am using `concurrent.futures` exclusively for my multi-threading needs and haven't had any issues. AFAIK, it is just higher level api for multi-threading, there is no magic. Are you sure it wasn't just some bug?

For example, [black](https://github.com/ambv/black) uses python 3.6 and it didn't really affect its popularity. There is a lot of great stuff in Python 3.6 and I think it is a push in the right direction. For my projects I use Python 3.6+. But of course, the decision is yours 😉

**Comment by dmfigol** [comment]
If I am going to work on this, is it ok to assume Python 3.6 syntax or I should use pre-3.6 syntax with comment? `# type: <your-type>`

**Comment by dbarrosop** [comment]
I don’t think we need to rewrite anything g asyncio, we will need to provide a new facility as you suggested though but in the end nornir may end up having a run and async_run modes. We will have to experiment a bit with this.

Regarding futures, to provide all that functionality there are bunch of very heavy classes that don’t scale well. You are free to test but while we could scale current solution to process thousands of devices in seconds, using futures took instead minutes.

Regarding py36+ syntax, go for it. I have a PR open already to get rid of anything <py3.6. Even though it’s going to make it harder for some people to use I think it’s worth it. Just for the sake of completeness, the comparison with black is not fair as you run black in your development machine or CI but nornir will end up running in bastions and control machines which sometimes are... heavily outdated. In any case, I think we should encourage people to containarize their nornir applications so we can focus on a writing clean and modern code.

**Comment by ktbyers** [comment]
I think this is done.

**Comment by dbarrosop** [comment]
It's not completed yet so I am going to reopen it. It's enabled for some modules only. I'd like to enable it everywhere before releasing 2.0 in case it leads to major refactorings.

**Comment by dbarrosop** [comment]
Closing this as I think it's completed
