### ISSUE TITLE
Add run method to Host and Group classes

### ISSUE THREAD

**Issue by dmfigol** [nornir-automation/nornir#164]
This is slightly related to #155 and #149
The pattern of running tasks on the group or on a specific host is very common. There were a couple of PRs trying to implement this using filters.
While I think F filters are a good idea, I think it would be great if you could also invoke `run` method directly on `Host` or `Group` class instance, something like this:
```
nornir_runner.inventory.hosts["sj-br1"].run(
    task=networking.napalm_get,
    name="Collecting facts using NAPALM",
    getters=["facts"],
)
nornir_runner.inventory.groups["sj-edge"].run(
    task=networking.napalm_get,
    name="Collecting facts using NAPALM",
    getters=["facts"],
)
```
Thoughts?

**Comment by ogenstad** [comment]
I think this is quite easy to do today using filters like this:

```python
result = nornir.filter(name="my_router").run(my_task)
```

Granted a useful method for filtering groups is still missing. For now, I think it would be best to leave it as is. If this were to get added, I think the next question from someone else would be "Which one is best practice?"

Do you think your suggestion is much different than my example?

**Comment by dbarrosop** [comment]
Targeting a host is already supported with `nr.filter(name="sj-br1")` and the filters discussed in #155 should allow you to do the equivalent for groups. I don't particularly mind your proposal but I think that before going with it we should make sure there is a clear advantage over existing methods to avoid overloading the API with redundant methods that might complicate things later on when trying to add other features.

**Comment by dmfigol** [comment]
I am currently using the mentioned method, but I do believe that my suggestion provides simpler abstraction for a very common use-case: select group, run task(s) for the group. In my Ansible projects, ~80% of my tasks are group-based, 15% host-based, 5% group-based excluding some devices.
With F filters the syntax for group selection the syntax is weird (albeit, it is good to have it!):
`nornir_runner.filter(filter_func=F(groups__contains="group_1")).run()`
vs
`nornir_runner.inventory.groups["group_1"].run()`

How I would separate it to avoid confusion for users:
- simple selection: host or group, using the proposed syntax
- any advanced filtering: `.filter()`, with or without F filters.

**Comment by dmfigol** [comment]
@dbarrosop now that F filters are merged, do you think we could add method `run` for hosts and groups which will invoke F filter with required parameters?

**Comment by dmfigol** [comment]
We were discussing this with David in Slack and reached the conclusion that we need more user feedback on this. Feel free to vote with thumbs up/down on the first post.
Since currently we decided to leave the existing behavior, I am going to close this.
