### ISSUE TITLE
Add attribute delegation __getattr__ to Host/Group for easy access to variables

### ISSUE THREAD

**Issue by dmfigol** [nornir-automation/nornir#167]
Currently it is possible to access arbitrary key-value pairs using `__getitem__`:
`switch1["my_key"]` or `switch1.get("my_key")`
Majority of variables available to the user are stored in `self.data` or accessed from the group hierarchy.
This change would make variable access even more beautiful using delegation, where all attempts to read new variables (or write - if taken to the extreme) would be delegated to methods of the attribute `data`.
You would be able to say:
`switch1.my_key` or `switch1.my_key = "value"`
Here is an (extreme) example that uses both read and write:
```python
class Host:
  __initialized = False
  def __init__(self, name):
    self.name = name
    self.data = {}

    self.__initialized = True

  def __getattr__(self, name):
    try:
        return self.data[name]
    except (AttributeError, KeyError):
        raise AttributeError(
            f"'{self.__class__.__qualname__}' object has no attribute '{name}'"
        )

  def __setattr__(self, name, value):
    if not self.__initialized or hasattr(self, name):
        super().__setattr__(name, value)
    else:
        self.data[name] = value
```
Usage:

```
In [21]: sw1 = Host(name="sw1")

In [22]: sw1.name
Out[22]: 'sw1'

In [23]: sw1.site
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-20-991bde2bf5b8> in __getattr__(self, name)
     10     try:
---> 11         return self.data[name]
     12     except (AttributeError, KeyError):

KeyError: 'site'

During handling of the above exception, another exception occurred:

AttributeError                            Traceback (most recent call last)
<ipython-input-23-2a572e3bc687> in <module>()
----> 1 sw1.site

<ipython-input-20-991bde2bf5b8> in __getattr__(self, name)
     12     except (AttributeError, KeyError):
     13         raise AttributeError(
---> 14             f"'{self.__class__.__qualname__}' object has no attribute '{name}'"
     15         )
     16

AttributeError: 'Host' object has no attribute 'site'

In [24]: sw1.site = "sj"

In [25]: sw1.__dict__
Out[25]: {'name': 'sw1', 'data': {'site': 'sj'}, '_Host__initialized': True}

In [26]: sw1.name
Out[26]: 'sw1'

In [27]: sw1.name = "new-sw"

In [28]: sw1.name
Out[28]: 'new-sw'

In [29]: sw1.__dict__
Out[29]: {'name': 'new-sw', 'data': {'site': 'sj'}, '_Host__initialized': True}
```
Read-only version will be simpler with less magic, but still could be useful

Thoughts?

**Comment by dbarrosop** [comment]
I'd like to hear the thoughts of @ogenstad and @ktbyers but I think this change has more cons than pros. For starters, you are mixing class attributes with object data by doing this, which is bad IMO for several reasons:

1. The object is supposed to be a dict-like object. So items, keys and values are supposed to iterate over the inventory data. Now you are mixing class attributes and object datapoints and the user starts wondering by `nornir_username` is not part of that iteration.
2. Brings a lot of inconsistencies, for instance, if you have two datapoints for your host named "myvar" and "my-var" you can do `host.myvar` while you can't do `host.my-var`.
3. You go to the API documentation and you are left wondering why some properties are documented and some others not (the ones generated dynamically).
4. Finally, if you name your variable like some class property either you shadow it (and potentially breaking the code) or you go back to the same inconsistencies in point 2 where not all the datapoints can be accessed in this way.

However, with the current method everything is very simple to reason about.

1. Attributes are defined by the class and come from nornir
2. Items belong to the instance and come from the inventory

And there is no risk of complicating things, bringing inconsistencies or even breaking things without noticing.

**Comment by dmfigol** [comment]
@dbarrosop I think your points are valid and there is no need to mix data and internal attributes. Since there were no other thoughts, I will just close this.
