### ISSUE TITLE
add how to access specific connections

### ISSUE THREAD

**Issue by dbarrosop** [nornir-automation/nornir#168]
Basically, explain how a user may be able to access a type of connection directly for the sake of working with it directly via `Host.connections` and `Host.get_connection`.

**Comment by ipv6freely** [comment]
I don't know if this is useful or the same thing this issue was raised for, but I used the following to manually get a generic RPC call, and not sure if it's the best way?
`task.host.connections["napalm"].device.rpc.get_ospf_interface_information()`

**Comment by dbarrosop** [comment]
for this particular use case we need a proper rpc connection plugin. In any case, yours is a good example of why it's interesting that people knows how to access the connections directly :)

**Comment by ipv6freely** [comment]
I actually already wrote one. Want a PR? :)

**Comment by ktbyers** [comment]
Closing...old.
