### ISSUE TITLE
Cleanly handle connection closure

### ISSUE THREAD

**Issue by lykinsbd** [nornir-automation/nornir#171]
As discussed on Slack and in PR #170 there is a need for some standard method of closing connections.

Closing PR #170 (specific to Netmiko, and without option to utilize connection reuse) to rework into a more general connection handling PR.

Moving comments over here.

From @dbarrosop :

> 
> As commented on slack, this basically removes the ability to reuse connections. We should probably have a "close" task for all the connection plugins we can call either automatically or manually. For instance, right below this (https://github.com/nornir-automation/nornir/blob/develop/nornir/plugins/tasks/connections/netmiko_connection.py#L12) we could have a netmiko_close_connection and have as many tweaks there as necessary. Then we could either let users call that task whenever they want with the tweaks they want or maybe even provide a Nornir.close_connections() function that closes all the open connections by calling those tasks with the default parameters (or maybe even reading from the configuration file). Any thoughts?
> 
> Two more reasons to not do it on the tasks:
> 
>     We'd have to implement on every task, existing or future for consistently.
>     If there is an exception of the task you may leave the connection hanging.
>

**Comment by dmfigol** [comment]
I think this is addressed with context manager and additional methods for connection handling described here: https://nornir.readthedocs.io/en/stable/howto/handling_connections.html
@lykinsbd could you please confirm?

**Comment by dbarrosop** [comment]
Is this one still relevant?

**Comment by lykinsbd** [comment]
This is resolved, sorry for the delay in seeing/closing!  Thank you!
