### ISSUE TITLE
nornir and asyncio

### ISSUE THREAD

**Issue by dmfigol** [nornir-automation/nornir#175]
asyncio allows to switch context during i/o operations in a single thread, usually it scales better than threads. The problem is it requires significant code rewrite to be able to support it.
I've stumbled upon apparently common pattern for asyncio integration into a synchronous code:
you start another thread to run asyncio loop and submit tasks there.
This issue is opened to track if this integration is possible. I will work on this next week.

**Comment by dmfigol** [comment]
I think I have use-cases for this. Python async web frameworks started getting a lot of interest in the industry. Most of my nornir use-cases are tied with a web framework, however I can't easily use nornir if I choose to use an async framework. If nornir was to support async and asyncio tasks natively, I could easily migrate and I wouldn't even need a separate task queue, everything could be handled in the web framework directly.  
Though, to be fair, besides an actual support from Nornir side, I'd also need async enable backends. There is asyncssh and netdev already (which are alternatives to paramiko and netmiko), but there isn't one for ncclient for example, at least for now.

**Comment by dbarrosop** [comment]
I played a bit with asyncio, check #390

**Comment by Ali-aqrabawi** [comment]
i suggest using twisted instead of asyncio framework to avoid rewriting everything, what do you think?

**Comment by ktbyers** [comment]
Going to close as this is not actively being worked on here.
