### ISSUE TITLE
Rework connections for 2.0

### ISSUE THREAD

**Issue by dmfigol** [nornir-automation/nornir#189]
This issue is to keep track of refactoring connections for 2.0.
I will try keeping the first post updated with all gathered requirements and potentially implementation details

### Requirements and ideas
1. Abstraction separation between connections and other tasks. Connections do not return Result, they populate connections dictionary for the host
2. Connections can be re-used between different tasks
3. There should be a way to close connections explicitly or implicitly (at the end of the program?)
4. Closing remaining connections gracefully on an unhandled exception in one worker
5. Unified API for connection open/close

#### PRs
~Refactor connection plugins #195~
Add class methods for plugins registration in Connections class #235 

#### Open Issues
* Rework global configuration options and their plugin specific counterparts #210
* Augment Connections class #211 WIP
* Support for several connections using the same ConnectionPlugin #207
* Consolidate inventory attributes #202
* NETCONF connection plugin #208
* VMware ESXi connection plugin #209

**Comment by dmfigol** [comment]
Anything missing on the list?
I will also clarify "extra". For my use-case we will manage devices mainly by SSH or NETCONF, however, there will be a situations where during one program, SSH is not available and I would like to fallback to using telnet to console to be able to manage device with the same plugin (`netmiko_send_config` for example)

**Comment by ogenstad** [comment]
>Connections are not tasks, they don't return results, hence probably should be separated from nornir.plugins.tasks

I don't know if this is just a wording issue or a matter of where the connection plugins are located. But I would still view them as tasks. While they connect automatically if you use another task that depend on them you might still want to establish the connections manually by calling that task. For example if someone was using Tacacs or Radius and didn't want everything to hit the authentication backend at once you might connect using a lower `num_worker`, then raise the number for the following tasks. Though, you might not be arguing against this only that the plugins should be placed elsewhere? Or that all plugins should return a result even though it's just an `ok` status.

Regarding the closing of connections. I think it would be good to be able to iterate through the inventory find all hosts that have active connections and close them all in a consistent way. I.e you should be able to gracefully close a paramiko connection and a napalm connection in the same way.

**Comment by dbarrosop** [comment]
Will send a PR soon with some ideas.

The only comment I have at this point is that this might be difficult to implement for a very specific set of corner cases:

>    There are tasks that can use different connections for one host (for example, netmiko plugins with ssh/telnet to console port), we should have a way to do that too

I'd assume that's easier to solve by having the user have different hosts (even though they point to the same one).

**Comment by dmfigol** [comment]
@ogenstad 
I re-worded a little, not sure if it helped. Connections are different abstraction from my perspective. I don't think they should return Result: they are either silent or throw an exception.
I also added point 5 based on your comment.
My 2 cents: when I am looking on the current list, the first thing that comes to mind is using classes (instead of functions), specifically abstract base classes to implement this. For example, having ABC for usual Task, returning Result object (may be some renaming here is necessary) and ABC for Connections. Plugin developer would need to inherit from it and to implement defined methods.

**Comment by dbarrosop** [comment]
Work being done in #195

**Comment by dmfigol** [comment]
@dbarrosop 
Looking at #195 and requirements 3 and 4 it got me thinking if we should implement a context manager for `Nornir` object. Since context manager `__exit__` method is injected before the exception is re-raised, it would be an easy way of closing connections gracefully on exit, regardless of what is happening in the program.
It will look something like this:
```
class Nornir
    ...
    def __enter__(self):
        return self
    def __exit__(self, exc_type, exc_val, exc_tb):
        self.close_all_connections()
```
and the usage would be:
```
with InitNornir("config.yaml") as nr:
    nr.run(...)
    # do anything
    # regardless if an exception was raised, it will go ahead and try closing all connections
```
This is the only clean way of closing connections gracefully that I know.
An alternative would be:
```
nr = InitNornir("config.yaml") as nr
try:
    nr.run(...)
    # do anything
finally:
    nr.close_all_connections()
```

**Comment by dbarrosop** [comment]
Ok, the only reason I don't like the context manager in this case is because I expect nornir code to be quite large and this adds yet another level of indentation. For very short code I think the context manager is great (like opening a file and loading a yaml from it) but for longer code it just becomes unnecessarily indented.

To implement the same functionality what I did was the following:

https://github.com/nornir-automation/nornir/pull/195/files#diff-66e84133a7666c12ec5daa228bcd5969R57

That will basically close the connection automatically when the garbage collector deletes the `Host` and its `Connections` object with it.

I am not super against the context manager so let me know what you think about my proposal and let's take it from there.

**Comment by dmfigol** [comment]
@dbarrosop 
https://docs.python.org/3/reference/datamodel.html#object.__del__
> It is not guaranteed that __del__() methods are called for objects that still exist when the interpreter exits.

The only thing I don't like about context managers is exactly what you said - another level of indentation. That said it is not a problem that can't be solved: you can always create a wrapper function which will take `Nornir` object:
```
def main(nr):
    # your nornir code

if __name__ == '__main__':
    with InitNornir("config.yaml") as nr:
        main(nr)
```

I think context managers are something that people are used to - you see them in any library that handles a connection to something: ssh / database / netconf / whatever.
I would like to see a context manager for nornir. At the same time there still should be a way to explicitly close connections without a context manager - in this case it would be a user's responsibility to close them using `nr.close_all_connections()` or whatever it is going to be called.

**Comment by dbarrosop** [comment]
Should we close this one as the bulk is done and the rest has independent tickets?

**Comment by dmfigol** [comment]
I suggest we keep it open. I will keep updating the first post with the current progress on individual issues.

**Comment by dbarrosop** [comment]
Closing this as I think it's completed
