### ISSUE TITLE
Plugins' dependencies

### ISSUE THREAD

**Issue by dmfigol** [nornir-automation/nornir#196]
I expect that plugins ecosystem will grow over time. At least some things that I am planning to work on are netconf and vmware connections.
The question is if main dependencies for plugins (netmiko, paramiko, napalm, ncclient, pyvmomi, etc.) should be `nornir` dependencies too or the docs should ask users to `pip install` them if they need that functionality?
From one perspective the number of dependencies and size of installation can grow indefinitely, but it will be easier for users.
From another perspective, users will save space, but would need to install libraries manually.

**Comment by dbarrosop** [comment]
There are three options:

1. As we refactor the plugins we could add the ability for plugins to describe their own dependencies:

```
@task(requirements = ["blah", "bleh"])
def my_plugin(task, ...):
    pass
```

(ignore the fact I am using a decorator) and then have code that installs the dependency at runtime if they are missing. This would install only dependencies for needed plugins.

2. A second option is to properly document which dependencies a plugin has and let the user define their own `requirements.txt` file in their project.

3. We could use the `pip install nornir[blah,bleh,blih]` trick but I have limited experience with it and I am not sure how well it will work.

**Comment by dmfigol** [comment]
Among these options I like 2) the most.

**Comment by dmfigol** [comment]
I would like to bring this up before we release 2.0
Should we remove paramiko, netmiko, napalm and requests from dependencies? Or this would be applicable only to newer dependencies?

**Comment by dbarrosop** [comment]
To be honest, I'd prefer to delay this until nornir 3.0. Dependencies are quite small as of now so I'd wait until 3.0 to avoid delaying 2.0 things even more. @ktbyers thoughts?

**Comment by ktbyers** [comment]
I would pretty strongly prefer to defer this until nornir 3.0.

**Comment by dbarrosop** [comment]
@dmfigol you ok with this? any strong reason against it?

**Comment by dmfigol** [comment]
yes, it is fine

**Comment by ogenstad** [comment]
A thought I had was to just have Task.start() catch an ImportError exception and format the output in some way. That way you wouldn't need to care about adding any kind of decorators to the plugin.

**Comment by dbarrosop** [comment]
Unfortunately it's not that simple as you may be masking other issues (ie a cyclic import), napalm suffered some of those when trying to do the same. In any case, I am not worried about the implementation, I am more worried about introducing too many changes and delaying the release even more.

**Comment by dbarrosop** [comment]
I am closing this one as it's not going to be a problem with the new architecture.
