### ISSUE TITLE
exit_status_code -1 by Huawei switch

### ISSUE THREAD

**Issue by senses0** [nornir-automation/nornir#201]
Hi,

I'm trying out the simple remote_command task on a Huawei switch. Even though there are no issue login in and executing commands, for some reason the exit_status_code is -1 instead 0, and therefore it is raised as a command error by remote_command.py module (Line 39 - 40)

I don't know enough about these exit codes to know if -1 is in fact an error, or just a non-standard Huawei implementation that says there was no error.

If I bypass this check condition for -1 status code in remote_command.py module, I do to get the switch output.

**Comment by dbarrosop** [comment]
Can you try using  the nemiko plugins instead? Maybe `netmiko_send_command` will work instead. `remote_command` expect as POSIX compliant system on the other side and I doubt huawei is.

**Comment by senses0** [comment]
Thanks for that.

How do I go about using netmiko within Nornir? Could not figure that out from the documentation :/

I tried SSH on Huawei with Netmiko library (independent of Nornir) and it seems to be working.

**Comment by ktbyers** [comment]
@senses0 Here is an example:

```
from nornir.core import InitNornir
from nornir.plugins.tasks.networking import netmiko_send_command
from nornir.plugins.functions.text import print_result


def main():

    # Initialize Nornir object using hosts.yaml and groups.yaml
    brg = InitNornir()

    result = brg.run(
        netmiko_send_command,
        num_workers=60,
        command_string="show ip int brief",
        use_textfsm=True,
    )

    print_result(result)


if __name__ == "__main__":
    main()
```

With hosts.yaml and groups.yaml in the same directory as the program:

```
$ cat hosts.yaml 
---
pynet-rtr1:
    nornir_host: cisco1.twb-tech.com
    groups: 
      - cisco-ios

pynet-rtr2:
    nornir_host: cisco2.twb-tech.com
    groups: 
      - cisco-ios

$ cat groups.yaml 
---
cisco-ios:
  nornir_nos: ios
  nornir_username: admin
  nornir_password: <password>
```

You would need to make the `norir_nos` match the Netmiko device_type.

**Comment by senses0** [comment]
Thanks! That worked... for the most part. 

From the looks of it, there is no issue login into the device and executing commands now. But for some reason, I'm not getting the output from the device.

Printed out the result as follows
`print_result(result, vars=['stdout'])`

`2018-07-31 10:13:19,222 -       nornir -     INFO -        run() - Running task 'netmiko_send_command' with num_workers: 50
2018-07-31 10:13:19,222 -       nornir -     INFO -        run() - Running task 'netmiko_send_command' with num_workers: 50
2018-07-31 10:13:19,223 -       nornir -    DEBUG -        run() - {'command_string': 'display timezone'}
2018-07-31 10:13:19,223 -       nornir -    DEBUG -        run() - {'command_string': 'display timezone'}
2018-07-31 10:13:19,240 -       nornir -     INFO -      start() - rtr-lab-01: netmiko_send_command: running task
2018-07-31 10:13:19,240 -       nornir -     INFO -      start() - rtr-lab-01: netmiko_send_command: running task
2018-07-31 10:13:19,243 -       nornir -     INFO -        run() - Running task 'netmiko_connection' with num_workers: 1
2018-07-31 10:13:19,243 -       nornir -     INFO -        run() - Running task 'netmiko_connection' with num_workers: 1
2018-07-31 10:13:19,243 -       nornir -    DEBUG -        run() - {}
2018-07-31 10:13:19,243 -       nornir -    DEBUG -        run() - {}
2018-07-31 10:13:19,243 -       nornir -     INFO -      start() - rtr-lab-01: netmiko_connection: running task
2018-07-31 10:13:19,243 -       nornir -     INFO -      start() - rtr-lab-01: netmiko_connection: running task
netmiko_send_command************************************************************
* rtr-lab-01 ** changed : False ******************************************
vvvv netmiko_send_command ** changed : False vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv INFO
^^^^ END netmiko_send_command ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Process finished with exit code 0`

**Comment by senses0** [comment]
Update:
I printed `result` variable in `netmik_send_command.py` before the return statement `return Result(host=task.host, result=result)`

Output from device exists in result variable at this point. My switch output looks like something like this

> The current time zone:  GMT+08:00

So this may have something to do with how the result gets processed by Result?

**Comment by ktbyers** [comment]
@senses0 You will need to post your code (or at least the relevant section of it).

**Comment by senses0** [comment]
@ktbyers 

See below. This is pretty much it. I have config.yaml, hosts.yaml and groups.yaml pretty much how it's described in the tutorial.

> from nornir.core import InitNornir
> from nornir.plugins.tasks.networking import netmiko_send_command
> from nornir.plugins.functions.text import print_result
> import logging
> 
> nr = InitNornir(config_file='config.yaml')
> 
> result = nr.run(
>     netmiko_send_command,
>     name='Timezone Info',
>     num_workers=50,
>     command_string='display timezone',
>     severity_level=logging.DEBUG
> )
> 
> print_result(result, vars=['stdout'])

**Comment by ktbyers** [comment]
@senses0 

I don't think you will be able to do print_result that just do `print_result(result)`.

This worked for me:

```
from nornir.core import InitNornir
from nornir.plugins.tasks.networking import netmiko_send_command
from nornir.plugins.functions.text import print_result
import logging

nr = InitNornir()

result = nr.run(
    netmiko_send_command,
    command_string='show ip int brief',
    num_workers=50,
)

print_result(result)
```

**Comment by senses0** [comment]
I did. Wouldn't still print out the results.

I also used netmiko_send_command on a linux host and issued "ls -l" (just to eliminate Huawei). Same result.

Again, if I printout the result variable within `netmiko_send_command.py` (before the return statement) I do see "ls -l" output

**Comment by ktbyers** [comment]
@senses0 Post your code please.

**Comment by dbarrosop** [comment]
Closing this as I don't think there is anything else to do. Feel free to open otherwise.
