### ISSUE TITLE
Host/Group abstraction separation

### ISSUE THREAD

**Issue by dmfigol** [nornir-automation/nornir#205]
Currently `Group` is inherited from `Host`, however we see more and more host-specific things implemented in the `Host` class, which have nothing to do with `Group`:
* connection handling
* properties like username, password, port, operating system

I propose to abstract the part where they are similar to a separate class (can't think of a great name, but something like `InventoryEntity`) so that public API for a `Group` remains clean.

**Comment by ktbyers** [comment]
FWIW, my username, password, and nos are generally in Groups not Hosts.

**Comment by dbarrosop** [comment]
Yeah, that'd would work the same way regardless of doing this work or not, which we should do although there is no rush as this is mostly an OCD improvement :)

**Comment by dbarrosop** [comment]
`InventoryElement`?

**Comment by dbarrosop** [comment]
This should be fixed now, otherwise feel free to reopen.
