### ISSUE TITLE
Merge Inventory parameters from config file and InitNornir call?

### ISSUE THREAD

**Issue by optiz0r** [nornir-automation/nornir#206]
Parameters passed to `InitNornir` currently take precedence over parameters defined in the nornir config file. Because inventory parameters are defined as a hash, that means if any one parameter is passed via the init function, all other parameters are defaulted out, rather than merged with what's in the configuration file.

I think it would be useful if they could be merged instead (probably just one level deep). My rationale for this is implementing a caching layer for fetching data from an custom inventory. I would like to define the cache file and expiration in the config file, but retain the ability to disable caching at runtime by passing an argparse argument through `InitNornir`.

```python
# currently
for k, v in kwargs.items():
    setattr(self, k, v)

# proposed alternative
for k, v in kwargs.items():
    if type(v) is dict:
        # merge dict values
        getattr(self, k).update(**v)
    else:
        # replace other value types
        setattr(self, k, v)
```

This this is acceptable, I can look at raising a PR with tests. There is a potential compatibility break here if people rely on the current behaviour.

**Comment by dbarrosop** [comment]
The problem I see with this proposal is that it is not general (neither it is the current implementation). What I mean with this is that no matter which option we use someone is going to be unhappy and think that some other behavior is more desirable. The main reasons why I would prefer to stick with the current approach are:

1. It is easy to reason about (kwargs take precedence)
2. If someone is going to be unhappy no matter what I do I will at least choose the solution that has the simpler implementation.

What I would recommend you to do is adding in your own code something like this:

```
def CustomInitNornir(..., **kwargs):
    nr = InitNornir(..., **kwargs)    
    for k, v in kwargs.items():
        if isinstance(v, dict) is dict:
            getattr(self, k).update(**v)
        else:
            # replace other value types
            setattr(self, k, v)
```

So in your own code you'd be calling your own `CustomInitNornir` instead of the vanilla one. Is this solution workable for you?

**Comment by optiz0r** [comment]
That works for me as long as the interface is expected to remain reasonably stable.

Do you think it's worth adding a note in the docs that while config file/InitNornir parameters can be combined (https://github.com/nornir-automation/nornir/blob/eba2a7103b45ea660a0e2d7217878a1a16871d55/docs/tutorials/intro/initializing_nornir.ipynb#L177), this does not hold true for inventory arguments?

**Comment by optiz0r** [comment]
I thought it might work, but looking closer it won't. The InitNornir method instantiates the Inventory object during the lifetime of the call, so once InitNornir() returns, it's too late to make any modifications.

As an alternative I tried the below, but it still can't work because it's the `Config` constructor which is losing the data stored in the config file. And I can't pop the class name off the kwargs any earlier because if the inventory class name is defined within the config file itself, there's no way to know before the Config constructor completes what it was going to be.

```python
def InitNornir(config_file="", dry_run=False, inventory_transform_function=None, **kwargs):
    conf = Config(config_file=config_file, **kwargs)
    inv_class = conf.inventory
    inv_args = getattr(conf, inv_class.__name__, {})

    if inv_class.__name__ in kwargs:
        inv_overrides = kwargs.pop(inv_class.__name__]
        inv_args.update(**inv_overrides)

    transform_function = conf.transform_function
    inv = inv_class(transform_function=transform_function, **inv_args)

    return Nornir(inventory=inv, dry_run=dry_run, config=conf)
```

The `Config` constructor is the only place that has access to all the necessary information (inventory class name, config file parameters for the inventory class, and the kwargs parameters from call to InitNornir), so is the only place any special handling can possibly take place without significant changes.

**Comment by dbarrosop** [comment]
> but it still can't work because it's the Config constructor which is losing the data stored in the config file

That's correct. I just tried this and worked as expected:

```
def CustomInitNornir(config_file="", dry_run=False, **kwargs):
    nr = InitNornir(config_file, dry_run)

    for k, v in kwargs.items():
        if isinstance(v, dict):
            t = getattr(nr.config, k, {})
            t.update(**v)
            setattr(nr.config, k, t)
        else:
            setattr(nr.config, k, v)

    return nr
```

With the following config.yaml:

```
test_dict:
    a: 1
    b: 2

test_int: 1
test_int2: 2
```

And calling it like this:

```
nr = CustomInitNornir(
    config_file="config.yaml", test_dict={"b": 22, "c": 3}, test_int2=333
)
```

I get:

```
(Pdb) nr.config.test_dict
{'a': 1, 'b': 22, 'c': 3}
(Pdb) nr.config.test_int
1
(Pdb) nr.config.test_int2
333
```

Which is what I think what you were looking for.

**Comment by dbarrosop** [comment]
If you require the special handling of attributes you can also do:

```
def CustomInitNornir(config_file="", dry_run=False, **kwargs):
    with open(config_file, "r") as f:
        yml = ruamel.yaml.YAML()
        data = yml.load(f) or {}

    for k, v in kwargs.items():
        if isinstance(v, dict):
            t = data.get(k, {})
            t.update(v)
            data[k] = t
        else:
            data[k] = v

    return InitNornir(dry_run, **data)
```

Which yields similar result:

```
(Pdb) nr.config.test_dict
CommentedMap([('a', 1), ('b', 22), ('c', 3)])
(Pdb) nr.config.test_int
1
(Pdb) nr.config.test_int2
333
```

**Comment by dbarrosop** [comment]
> by the first line of the function, and not (a:1, b:22, c:3) which is the desired behaviour

That's the way the second alternative I sent you works

> But then InitNornir is going to re-read the same config file again

That example doesn't pass the config_file to InitNornir

**Comment by dbarrosop** [comment]
I am closing this one as I think there is nothing else to do. Feel free to reopen if you think there is still something to do/discuss here.

If you want to contribute a generic how to on how to tweak `InitNornir` that'd be greatly appreciated
