### ISSUE TITLE
NETCONF connection plugin

### ISSUE THREAD

**Issue by dmfigol** [nornir-automation/nornir#208]
Add support for NETCONF connection plugin using `ncclient`.
I will work on this after #195 is merged.

**Comment by lemonTreeN7** [comment]
Is it still on the roadmap to have this netconf plugin? Same question for restconf?

**Comment by dbarrosop** [comment]
Restconf is just http requests with no stateful connection so you can just use the `requests` library directly, no need for a connection plugin in this case. If we wanted to have a generic http connection as a placeholder for headers we could look into that but I don't expect to see a specific Restconf plugin as there is nothing special there, just good old fashioned http requests.

Re netconf, yes, I'd like to see the plugin. It's not on my radar though and unfortunately it looks like @dmfigol's hasn't been able to find the time to work on this. If someone else wants to look at it I'd be happy to help/guide.

**Comment by dbarrosop** [comment]
I wrote a quick prototype in #416. I'd like to see some feedback, how people intends to use it (to write tasks or just leave it as a shim layer) and I'd like help testing it.

**Comment by itheodoridis** [comment]
Hi David, it's funny to be talking together through so many platforms (slack, twitter, nornir forum, etc). What kind of testing do you have in mind? Maybe I can help a little but keep in mind I am nothing like Dmitry in development skills. I can help with some testing by doing read only ops but no so much with configuration, unless we find a way to do this in a simulation tool.
Let me know through any means, twitter, slack, here, wherever.

**Comment by ogenstad** [comment]
Closing as this was added in #416.
