### ISSUE TITLE
Nornir spitting garbage along with output (Windows)(Anaconda prompt)

### ISSUE THREAD

**Issue by rapavin** [nornir-automation/nornir#234]
i have been testing out nornir for a bit, Its cool. Thank you Mr david and kirk.

here is the output where i am seeing some garbage. is there someway of removing these guys from the result ?

(base) C:\Users\Administrator\Downloads\Nornir\inventory>python test.py
[1m[36mnetmiko_send_command************************************************************[0m
[0m[1m[34m* S1 ** changed : False ***********************************************[0m
[0m[1m[32mvvvv netmiko_send_command ** changed : False vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv INFO[0m
[0mmage stamp:    /ws/swbuildm/maint_spokane_qaoff/code/build/anm(swbuildm_maint_spokane_qaoff_maint_spokane)
                Dec 21 2017 21:31:30
                WB.16.02.0022m
                789
Boot Image:     Primary

Boot ROM Version:    WB.16.03
Active Boot ROM:     Primary
[0m
[0m[1m[32m^^^^ END netmiko_send_command ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^[0m
[0m

Thanks

**Comment by ktbyers** [comment]
@rapavin Yes, those are Ansi escape codes that they are using to color the screen. You probably need to write your own output printer.

Here is an example function I used:

```
def std_print(agg_result):
    print()
    for k, multi_result in agg_result.items():
        print('-' * 50)
        print(k)
        for result_obj in multi_result:
            if isinstance(result_obj.result, str):
                print(result_obj.result)
            else:
                pprint(result_obj.result)
        print('-' * 50)
        print()
    print()
```

**Comment by rapavin** [comment]
This is my code.

from nornir.core import InitNornir
from nornir.plugins.tasks.networking import netmiko_send_command
from nornir.plugins.functions.text import print_result

nr = InitNornir()

hope = nr.run(
	task=netmiko_send_command,
	command_string="sh arp"

)

#print_result(result)
#print(result)
def std_print(hope):
    print()
    for k, multi_result in hope.items():
        print('-' * 50)
        print(k)
        for result_obj in multi_result:
            if isinstance(result_obj.result, str):
                print(result_obj.result)
            else:
                pprint(result_obj.result)
        print('-' * 50)
        print()
    print()
std_print(hope)


i am able to change the output, but still i am getting the ANSI escape code.

this is the output

(base) C:\Users\Administrator\Downloads\Nornir\inventory>python test.py

[0m--------------------------------------------------[0m
[0mZIA-TEACHER-2920[0m
[0m IP ARP table

  IP Address       MAC Address       Type    Port
  ---------------  ----------------- ------- ----
  172.20.20.1      000000-0000     dynamic Trk1

[0m--------------------------------------------------[0m

**Comment by dbarrosop** [comment]
hi, it's very hard to read your comments as they are not properly formatted. In any case, I'd recommend you to use cygwin or whatever preferred method windows has nowadays for POSIX compliance.

**Comment by rapavin** [comment]
i am using anaconda mr barroso. 

this is the output again. i have 6 switches and command is sh arp.

It is spiting out a lot of ANSI Escape characters.

(base) C:\Users\Administrator\Downloads\Nornir\inventory>python test.py

[0m--------------------------------------------------[0m
[0mZIA-TEACHER-2920[0m
[0m IP ARP table

  IP Address       MAC Address       Type    Port
 
  172.20.20.1      007888-e3f8c7     dynamic Trk1

[0m
[0m--------------------------------------------------[0m
[0m
[0m--------------------------------------------------[0m
[0mZIA-Port3-2920[0m
[0m IP ARP table

  IP Address       MAC Address       Type    Port

  172.20.20.1      007888-e3f8c7     dynamic Trk1

[0m
[0m--------------------------------------------------[0m
[0m
[0m--------------------------------------------------[0m
[0mZIA-Port2-2920[0m
[0m IP ARP table

  IP Address       MAC Address       Type    Port

  172.20.20.1      007888-e3f8c7     dynamic Trk1

[0m
[0m--------------------------------------------------[0m
[0m
[0m--------------------------------------------------[0m
[0mZIA-Port1-2920[0m
[0m IP ARP table

  IP Address       MAC Address       Type    Port

  172.20.20.1      007888-e3f8c7     dynamic Trk1

[0m
[0m--------------------------------------------------[0m
[0m
[0m--------------------------------------------------[0m
[0mZIA-PE-2920[0m
[0m IP ARP table

  IP Address       MAC Address       Type    Port

  172.20.20.1      007888-e3f8c7     dynamic Trk1

[0m
[0m--------------------------------------------------[0m
[0m
[0m--------------------------------------------------[0m
[0mZIA-BOOKROOM-2920[0m
[0m IP ARP table

  IP Address       MAC Address       Type    Port

  172.20.20.1      007888-e3f8c7     dynamic Trk1

[0m
[0m--------------------------------------------------[0m
[0m
[0m

**Comment by ktbyers** [comment]
@rapavin You can't use this:

```
from nornir.plugins.functions.text import print_result
```

This uses ansi escape codes which your terminal doesn't support.

You can use that alternate code I posted above.

**Comment by rapavin** [comment]
thank you, it worked
