### ISSUE TITLE
raise_on_error=True and NornirExecutionError

### ISSUE THREAD

**Issue by dmfigol** [nornir-automation/nornir#236]
When I am using `raise_on_error=True` and an exception from task is raised, it is wrapped into `NornirExecutionError` and raised.
I think we could improve this, but not wrapping task exception in this case and raise the original exception. This allows to catch specific library errors and react to them.

**Comment by dbarrosop** [comment]
How will you know which hosts failed then?

**Comment by dmfigol** [comment]
this was not very smart suggestion, I am closing this.
