### ISSUE TITLE
Create a modified host_vars and group_vars inventory plugin

### ISSUE THREAD

**Issue by ktbyers** [nornir-automation/nornir#238]
I am thinking about creating a modification to SimpleInventory or a different inventory plugin that had the Ansible `group_vars` and `host_vars` concept in a simplified form. 

Something like:

```
$ tree .
.
├── groups.yaml
├── group_vars
│   ├── ios
│   ├── junos
│   └── nxos
├── hosts.yaml
└── host_vars
    ├── host1
    ├── host2
    └── host3
```

Where any `*.yaml` files in group_vars/group_name or in host_vars/host_name would be included in inventory (in addition to processing hosts.yaml and groups.yaml). If used with SimpleInventory, you could add some parameter `enable_directories=True`

I would probably not want to name it host_vars and group_vars just to make it clear it is not Ansible and we are not following the rules of ansible inventory.

I like the group_vars and host_vars flexibility, but don't really want some other aspects of using the Ansible pluggin. 

No ansible name mappings. No ansible INI-style format. No trying to maintain compatibility with Ansible inventory format across time. Also only directory processing so it wouldn't support group_vars/group_name.yaml or host_vars/host_name.yaml processing.

Looking for feedback before I do much work here.

**Comment by dmfigol** [comment]
I had the same thoughts. I definitely need `host_vars` almost in my every application, while I am able to fit all my group variables in groups.yaml, but I understand that everyone's use-case is different.
+1 from me to adding this to `SimpleInventory`.
Instead of `enable_directories` we could add some flexibility for a user, by having:
```
host_vars_dir: <dir1>
group_vars_dir: <dir2>
```

**Comment by dbarrosop** [comment]
So I have been thinking about this and I think a separate function that provides this functionality would make more sense. For two reasons, one "philosophical" and another one "technical":

First the philosophical, people tends to conflate "inventory" and "data". The inventory is meant to provide host information and enough metadata  to classify hosts. For instance, things like "site", "roles", "classes", etc are things that are useful in the inventory to make sure we can filter them appropriately and work on them. Data, however, is meant to have significance for specific operations, for instance, BGP information might be needed when configuring routing but completely unnecessary when retrieving interface stats from the devices. This might be seem purely theoretical and philosophical but the truth is that if you are managing thousands of devices with hundreds of interfaces and hundreds of BGP peers and whatnot this means having to load a buckload of data each time regardless of if you need it or not.

The technical reason is that having a dedicated function for this allows you to use this regardless of the inventory you are using. For instance, if you are using nsot you may have some information there but for reason A or B you might not be able to store everything, in which case having this functionality as a task might be useful. From a usability perspective I think it's also interesting as you may be able to do things like this:

```
# Script to configure BGP
nr = InitNornir(...) # we don't care about the inventory plugin being used
load_host_vars(nr, path="./bgp", dst="bgp")

# Script to configure Interfaces
nr = InitNornir(...) # we don't care about the inventory plugin being used
load_host_vars(nr, path="./interfaces", dst="interfaces")
```
This pattern has two extra benefits:

1. We can narrow down the hosts we need data for: `load_host_vars(nr.filter(...) ,...)`
2. If we want to implement other patterns we don't need to keep adding complexity to `SimpleInventory` or tell people "no".

Thoughts?

**Comment by dmfigol** [comment]
I would love to have it as part of SimpleInventory so that users need to do less, since it is very common task, but I also agree with your reasoning.
In this case, shouldn't it be a method of Nornir class?

**Comment by ktbyers** [comment]
What if we do what you describe above and add an environment variable and config parameter that enables the automatic loading of this for SimpleInventory (loads all of the variables)?

**Comment by dbarrosop** [comment]
Somehow I lost track of this.

> What if we do what you describe above and add an environment variable and config parameter that enables the automatic loading of this for SimpleInventory (loads all of the variables)?

Fine by me, I'd use an argument though as that means we get for free the ability to toggle this via a configuration option or env variable

**Comment by ktbyers** [comment]
No worries. I had gotten side-tracked anyways. I will probably see if I can revisit this in Q1 2019.
