### ISSUE TITLE
Explore adding Pydantic for Config schema

### ISSUE THREAD

**Issue by dmfigol** [nornir-automation/nornir#239]
Started using `Pydantic` for data validation/serialization/deserialization recently for my project at work and I really like it.
We could use their [`BaseSettings` class](https://pydantic-docs.helpmanual.io/#settings)

**Comment by dbarrosop** [comment]
I was working on that already: #241

I need to look into the other PR you opened about logging because I think we stepped on each other.

**Comment by ktbyers** [comment]
This shouldn't be needed any longer.
