### ISSUE TITLE
Install Nornir on windows server 2012

### ISSUE THREAD

**Issue by mehdiskep** [nornir-automation/nornir#242]
Hello,
 
Could you please help me to install the framework on windows 2012? what are the steps to follow?
While I am working on a python script, i found your framework very usefull to my activity ( remote CLI and push/retreive commands). I am not very familiar even with python.

Thank you for you help :)

**Comment by dbarrosop** [comment]
I am afraid I am not familiar with windows server 2012 operations so I can't help you. I haven't even used Windows myself for 10+ years but I heard windows supports now running linux so I'd start there. Otherwise, I think anaconda is popular among windows user.

**Comment by ktbyers** [comment]
I had a different person indicate that it worked on Windows 10. See this thread:

https://github.com/ktbyers/pynet/issues/14#issuecomment-416966599

I suspect this was probably Nornir 1.1, however. You might want to discuss the setup with him.

I think there might be issues with Nornir 2.X and windows i.e. are new YAML parser might not be directly compatible with Windows.
