### ISSUE TITLE
add 'base path' configuration option

### ISSUE THREAD

**Issue by p-sherratt** [nornir-automation/nornir#244]
It'd be nice to have a configurable base/environment path, to be prefixed on the path of all task and plugin file operations.  This helps keep the user's codebase environment-agnostic.

**Comment by dbarrosop** [comment]
Why not use the PYTHONPATH?

**Comment by p-sherratt** [comment]
I didn't phrase the question/context clearly...  I mean for example the write_file task would prefix a configurable base path to 'filename'.  i.e. sharing the same python environment across different inventories, with different output file/template locations for each inventory.

Maybe it is cleaner though to have us code this up as users, rather than in the distribution.  e.g. subclass InitNornir to take 'environment' rather than config_file, and a dirty sys.chdir to the right place, or augment every path variable ourselves in every 'playbook'.  It felt like a pretty common use-case that could be catered for by Nornir itself.

**Comment by dbarrosop** [comment]
the path of those tasks don't assume anything, you are free to use an absolute or a relative path depending on what you want to do, if you want to use a configurable path that depends on the inventory I'd recommend using `defaults`. For instance:

```
nr = InitNornir(...)
base_path = nr.groups["defaults"]["base_path"]

nr.run(task=write_file,
       filename=f"{base_path}/something",
       content="blah")
```

Does this sound reasonable or where you thinking about something else?

**Comment by p-sherratt** [comment]
Yep, it seems much cleaner to define it in the inventory- thankyou! 👍
