### ISSUE TITLE
document netbox plugin

### ISSUE THREAD

**Issue by dbarrosop** [nornir-automation/nornir#249]
@bdlamprecht looks like we forgot to document it. If you have the time I'd appreciate if you can help out with that :)

**Comment by bdlamprecht** [comment]
I'm currently on vacation and will return in the beginning of August.  I'd be happy to help at then.

**Comment by dbarrosop** [comment]
beginning of august? Being mid-september now it's going to be a really nice and long vacation ;)

**Comment by bdlamprecht** [comment]
Yeah, you can tell I'm really on vacation as my mind is really all over the place. :stuck_out_tongue_winking_eye: 

That should have been the beginning of **October**.

Thanks for catching that.

**Comment by bdlamprecht** [comment]
I'm back from vacation now and looking to get everything taken care of that needed my attention.
Exactly what do you need documented and where?

Also, this plugin was developed with `v2.3.5` of NetBox, seeing as `v2.4.5` is being [developed](https://github.com/digitalocean/netbox/blob/develop/CHANGELOG.md), I'm wondering if it would be worthwhile for that to be released?

Let me know and I'll do my best.

**Comment by dbarrosop** [comment]
We can start by just adding a docstring and linking it into sphinx. My guess is that updating the plugin to work with 2.4.5 won't change any of that (if anything at all)

**Comment by ktbyers** [comment]
No longer relevant to core nornir repo (netbox plugin specific).
