### ISSUE TITLE
Add new group to inventory.groups after inventory initiation 

### ISSUE THREAD

**Issue by walidamer711** [nornir-automation/nornir#256]
I have successfully done Netbox inventory InitNornir initiation and I need to add a new group to inventory.groups. 
So, how to add a new group to inventory.groups after inventory initiation. Also, if this new group is added to the host after initiation, could the host populate the information from this group.

**Comment by walidamer711** [comment]
I have managed to add new group as described below.

from nornir.core import InitNornir
from nornir.core.inventory import Group
nr = InitNornir(config_file="config.yaml")
group_details = {"vlan": 10}
g2 = Group(name="switches", nornir=nr, **group_details)
nr.inventory.groups["switches"] = g2
nr.inventory.groups["switches"]
Group: switches
nr.inventory.groups["switches"].data
{'name': 'switches', 'vlan': 10}

then i add this group to one of the hosted as below.

rg2 = {'groups': ['switches']}
nr.inventory.hosts["r1"]["groups"].append("switches")
nr.inventory.hosts["r1"]["groups"]
['routers', 'switches']
nr.inventory.hosts["r1"].items()
dict_items([('name', 'r1'), ('groups', ['routers', 'switches']), ('hostname', '172.16.10.11'), ('platform', 'ios'), ('type', 'network_device'), ('role', 'router'), ('asn', 12345), ('username', 'cisco'), ('password', 'cisco'), ('domain', 'lab.net'), ('site', 'home')])

as seen above, the new group information (vlan) is not shown along with the host.
I am not sure what is the best way to implement this.

**Comment by dbarrosop** [comment]
which version of nornir are you using? We need to find a generic way of doing this that works for all of the inventories that don't support groups natively. We have had some discussions already but we haven't worked on that yet. Also, in the meantime the best way of fixing this would be extending the current netbox plugin.

**Comment by walidamer711** [comment]
I am running 2.0 at the moment. I am happy to here that you would consider this.
as a quick workaround for now I have grabbed the vlan information from the netbox through the api similar to the host inventory call int the netbox plugin and I have passed this information direct to the hosts.

def get_dc_vlans(tenant, group):
    headers = form_headers()
    query_params = {"tenant": tenant}

    vlans_netbox_dict = requests.get(
        NETBOX_API_ROOT + NETBOX_VLANS_ENDPOINT,
        params=query_params, headers=headers
    ).json()
    d = {}
    f = {}
    access_vlans = []
    agg_vlans = []
    for v in vlans_netbox_dict["results"]:
        if v["role"]["slug"] == "inside" or v["role"]["slug"] == "dmz":
            # Create temporary dict
            temp = {}
            temp["name"] = v["name"]
            temp["id"] = v["vid"]
            temp["role"] = v["role"]["slug"]
            access_vlans.append(temp)
            agg_vlans.append(temp)
        else:
            temp = {}
            temp["name"] = v["name"]
            temp["id"] = v["vid"]
            temp["role"] = v["role"]["slug"]
            agg_vlans.append(temp)
    if group == "dc-access":
        d["vlans"] = access_vlans
        f[group] = d
        return f
    elif group == "dc-aggregation":
        d["vlans"] = agg_vlans
        f[group] = d
        return f
    else:
        return None


vlans_group = get_dc_vlans("tenant", "dc-access")
inventory.hosts[f'{task.host.name}'].data.update(vlans_group)

**Comment by dbarrosop** [comment]
Great, I am closing this one as the discussion around generalizing how to deal with groups is being done in the issue #238. Feel free to keep commenting here though if you have specific questions about your workaround
