### ISSUE TITLE
Inventory hostname not set when Ansible inventory file is used

### ISSUE THREAD

**Issue by pehruby** [nornir-automation/nornir#278]
When a host is specified in Ansible inventory file by FQDN (i.e ansible_host variable is not set), Nornir 2.0.0b2 uses the FQDN in 'name' key and not in 'hostname' key which is set to None. This causes an Exception: ValueError('Either ip or host must be set') in napalm_get task.

As a workaround the following transform function can be used:

```
def adapt_host_data(host):
    if not host.hostname and host.name:
        host.hostname = host.name
```

Related part of hosts.yaml file:
```
                    hosts:
                      r1.domain:
                      r2.domain:
```

**Comment by carlniger** [comment]
I know this is old and your work around of course works, but if you set `ansible_host` in your ansible inventory the hostname will be populated w/ that value. 

```
arista1:
  ansible_host: arista1.supercooldomain.io
```

Given the above host somewhere in my inventory, I end up w/ the following:

```
ipdb> nr.inventory.hosts['arista1'].name
'arista1'
ipdb> nr.inventory.hosts['arista1'].hostname
'arista1.supercooldomain.io'
```

HTH!

**Comment by dbarrosop** [comment]
I am afraid I don't understand the problem. How does the inventory look like, what's the resulting inventory and what would you expect?

**Comment by carlniger** [comment]
I don't think there is a "problem" (no bug/issue).

The situation is that w/out having `ansible_host=XYZ` in the Ansible inventory the `hostname` value in Nornir host is left empty. 

Case1 - no `ansible_host` set in Ansible inventory:
```
$ cat ansible-hosts | grep arista1
arista1

ipdb> arista = nr.inventory.hosts['arista1']
ipdb> arista.name
'arista1'
ipdb> arista.hostname
ipdb>
```

Case2 - `ansible_host` set in Ansible inventory:
```
$ cat ansible-hosts | grep arista1
arista1 ansible_host=arista1.lasthop.io

ipdb> arista = nr.inventory.hosts['arista1']
ipdb> arista.name
'arista1'
ipdb> arista.hostname
'arista1.lasthop.io'
```

The transform function that @pehruby posted or just having `ansible_host=XYZ` set in the ansible inventory "fixes" this. I suspect this should be closed I was just trying to tack on some more details for future internet folks searching on things.

**Comment by dbarrosop** [comment]
Closing for now due to lack of activity. If someone wants to propose a fix in the inventory plugin feel free to do so.
