### ISSUE TITLE
Adding parameterers to connection_options raising hostname error

### ISSUE THREAD

**Issue by walidamer711** [nornir-automation/nornir#279]
When trying to add connection_options to the host through the transform function, it is raising the below error.

> Traceback (most recent call last):
 File "/home/wamer/.local/lib/python3.6/site-packages/nornir/core/task.py", line 62, in start
   r = self.task(self, **self.params)
 File "/home/wamer/.local/lib/python3.6/site-packages/nornir/plugins/tasks/networking/netmiko_send_command.py", line 26, in netmiko_send_command
   net_connect = task.host.get_connection("netmiko", task.nornir.config)
 File "/home/wamer/.local/lib/python3.6/site-packages/nornir/core/inventory.py", line 296, in get_connection
   **self.get_connection_parameters(connection).dict(),
 File "/home/wamer/.local/lib/python3.6/site-packages/nornir/core/inventory.py", line 230, in get_connection_parameters
   hostname=r.hostname if r.hostname is not None else self.hostname,
AttributeError: 'dict' object has no attribute 'hostname'

Code like this:

```python
 r = InitNornir(core={"num_workers": 100},
                    inventory={"plugin": "nornir.plugins.inventory.netbox.NBInventory",
                               "options": {"nb_url": "http://url", "nb_token": ""}, 
                               "transform_function": add_conn_options,})
```
```python
 def add_conn_options(host):
    host.username = "admin"
    host.password = "admin"
    host.connection_options["netmiko"] = ConnectionOptions(extras= {'secret': 'admin'})
```

Printing the connection_options is a dict:

```python
print(hosts.inventory.hosts["DCFW"].connection_options)
```
> {'netmiko': {'extras': {'secret': 'admin'}}}

**Comment by dbarrosop** [comment]
Could you format the issue with markdown so it's readable, please? It's hard to read as it is right now.

Thanks!

**Comment by walidamer711** [comment]
I have edited the issue with markdown :)

**Comment by ktbyers** [comment]
Error indicates there is `no hostname`

```
hostname=r.hostname if r.hostname is not None else self.hostname,
AttributeError: 'dict' object has no attribute 'hostname'
```
