### ISSUE TITLE
Passing arguments to inventory transform_function

### ISSUE THREAD

**Issue by optiz0r** [nornir-automation/nornir#290]
Hi all,

I'm using the `transform_function` in what I think is a fairly canonical way, to pass host authentication data (and other configuration secrets) from a secrets storage system into the inventory data (which initially contains only non-sensitive data) so that nornir can connect to hosts. Because the transform function has never accepted any arguments other than the current `host`, I've done this in the past using function currying, and lexical scoping (example below).

Under nornir v2 this no longer works as the transform_function is serialised to a string, using a custom `cls_to_string` method which doesn't handle anonymous functions/lambdas at all (it naively generates a bogus path name). I would like to find a way to continue to support this in v2+.

Example:
```python
# Reusable function in a library, which isn't concerned with where the auth data comes from
def transform(auth_data):
  def _transform(host):
    if not auth_data:
      return
    # Pass in user/pass for nornir to use during connection
    if 'username' in auth_data:
      host.data['nornir_username'] = auth_data['username']
    if 'password' in auth_data:
      host.data['nornir_password'] = auth_data['password']
    # Store a copy of the auth data for use by other tasks
    host.data['auth_data'] = auth_data
  return _transform # partially curried function

# nornir script
auth_data = retrieve_from_secrets_system(token=os.env['SECRET_TOKEN'])

nr = InitNornir(
    config_file="config.yaml",
    dry_run=True,
    inventory={
        'plugin': 'netops.inventory.foo.FooInventory',
        'transform_function': transform(auth_data), # fully-curry the transform function with the auth data
    }
)
```

Currently fails with:
``` 
File "/data/home/brobert/git/netops/env3/lib64/python3.6/site-packages/nornir/init_nornir.py", line 43, in InitNornir
    conf = Config.load_from_file(config_file, **kwargs)
  File "/data/home/brobert/git/netops/env3/lib64/python3.6/site-packages/nornir/core/deserializer/configuration.py", line 172, in load_from_file
    return Config.deserialize(**{**config_dict, **kwargs})
  File "/data/home/brobert/git/netops/env3/lib64/python3.6/site-packages/nornir/core/deserializer/configuration.py", line 158, in deserialize
    inventory=InventoryConfig.deserialize(**c.inventory.dict()),
  File "/data/home/brobert/git/netops/env3/lib64/python3.6/site-packages/nornir/core/deserializer/configuration.py", line 59, in deserialize
    transform_function=_resolve_import_from_string(inv.transform_function),
  File "/data/home/brobert/git/netops/env3/lib64/python3.6/site-packages/nornir/core/deserializer/configuration.py", line 183, in _resolve_import_from_string
    return getattr(module, obj_name)
AttributeError: module '__main__' has no attribute '_transform'
```

I understand passing through the anonymous function pointer is no longer going to work because of serialisation/deserialisation. Would you consider adding a `transform_function_options` parameter that would pass through `InventoryConfig` as either a single serialisable value, or as `**kwargs` to permit this use case going forwards?

Happy to work on a PR if so.

Thanks,
Ben

**Comment by dbarrosop** [comment]
Ok, I think having a `transform_function_options = {...}` makes sense.  To make sure we are on the same boat, that'd mean you will writ your function as:

```
def transform(host, auth_data):
    ...
```

And call it like:

```
nr = InitNornir(
    config_file="config.yaml",
    dry_run=True,
    inventory={
        'plugin': 'netops.inventory.foo.FooInventory',
        'transform_function': transform,
        'transform_function_options': {"auth_data": auth_data},
    }
)
```

Is this what you were also thinking about? If so, feel free to work on the PR and don't hesitate to ping me if you need help.
