### ISSUE TITLE
readthedocs v2 page title still shows version 0.0.1 in the title

### ISSUE THREAD

**Issue by robobeaver6** [nornir-automation/nornir#301]
The  [readthedocs page](https://nornir.readthedocs.io/en/latest/) shows an incorrect title for the page.

From the page source:
`<title>Welcome to nornir’s documentation! — nornir 0.0.1 documentation</title>`

**Comment by dbarrosop** [comment]
Thanks for this, #305 should fix this issue although the fix won't be reflected until next release.
