### ISSUE TITLE
Additional Nornir 1 to 2 Documentation

### ISSUE THREAD

**Issue by lykinsbd** [nornir-automation/nornir#317]
While working on converting an existing Nornir 1 install to 2.0.0, I encountered some additional items that need to be documented in the 1-to-2 docs:
 - Details on exactly how to convert earlier `config.yaml` syntax to the 2.0 syntax, for example moving from `logging_file:` to `logging:\n  file:`
 - Arbitrary/custom values in a SimpleInventory YAML file need to be moved into the `data` element
 - `netmiko_option` values in a SimpleInventory YAML file need to be now nested under: `connection_options -> netmiko -> extras`

I'm sure there are others, those are just the ones I encountered myself.  I will work up a PR to address a few of these.

**Comment by papo483** [comment]
In "Upgrading to nornir 2.x from 1.x" there is missing information that devices specific configuration structure has to be placed under "data:".

**Comment by dmfigol** [comment]
After a year I think it is not really relevant anymore, we haven't seen many reports of people still using 1.x. I will close this issue
