### ISSUE TITLE
Getting ansii color characters in output

### ISSUE THREAD

**Issue by bradh11** [nornir-automation/nornir#319]
When running a simple nornir script to get napalm facts, my results are getting bogus characters in the output.  I have tried it in the following terminals:
1. git-bash (windows)
2. windows CMD (windows 10)
3. powershell (windows 10)

in all cases my print_result(results) output is pretty messed up with ansii color characters.  I did not notice this issue in earlier versions of nornir.  Is it possible this started with the introduction of colorama?

![image](https://user-images.githubusercontent.com/18483910/52598346-700acd80-2e23-11e9-8821-a9d211f1860f.png)

**Comment by dbarrosop** [comment]
colorama has always been there. For instance, this version is from even before the project was called nornir and it's already there:

https://github.com/nornir-automation/nornir/commit/ec1bea77b8145fcbe02da0a50d14aab7d8073cbc#diff-1479d9baaf86a167cf3f1e63d66b390cL5

If this is a new issue for you I'd try downgrading/upgrading colorama and see if that fixes the issue and then we can discuss how to proceed but as you can see here colorama is meant to work even on windows cmd: https://pypi.org/project/colorama/

**Comment by dbarrosop** [comment]
Also, notice ANSI colors are interpreted by the terminal, not the shell. So make sure your terminal supports them, specially if you have changed terminal emulator recently.

**Comment by bradh11** [comment]
@dbarrosop  - I tested with 5-6 different versions of colorama, none of which worked.  That said, i did some further debugging/research and found a fix.  I am thinking it maybe something you might want to consider when nornir initializes?

`from colorama import init, deinit

deinit()
init(convert=True)
`

**Comment by ktbyers** [comment]
I see this in the colorama docs:

```
On Windows, calling init() will filter ANSI escape sequences out of any text sent to stdout or stderr, and replace them with equivalent Win32 calls.
```

**Comment by bradh11** [comment]
@ktbyers - Just tested and that did fix it.  Any negatives to making this change you can think of?  Would you like me to create a PR?

**Comment by dbarrosop** [comment]
yes, please, send a PR. Thanks!

**Comment by dbarrosop** [comment]
Thanks!

**Comment by bradh11** [comment]
ok, i had time to do some more testing.  There is an issue with the colorama init "convert" method.  

###  Test results:
### `init(autoreset=True, convert=False, strip=False)`
* Windows 10 systems get the ansii character codes instead of colors in the terminal.  (aka garbled text)
* 'nix systems get correctly colored text
* Jupyter notebook gets correctly colored text

### `init(autoreset=True, convert=True, strip=False)`
* Windows 10 systems get correctly colored text
* 'nix systems get correctly colored text
* Jupyter notebook gets plain text with no ansii color codes

### `init(autoreset=True, strip=False)`
* Windows 10 systems get correctly colored text
* 'nix systems get correctly colored text
* Jupyter notebook gets correctly colored text

I am starting to think it may be best to remove the convert parameter altogether unless there was a reason it was added in the first place?
