### ISSUE TITLE
unable to install nornir on ubuntu terminal

### ISSUE THREAD

**Issue by mkazam** [nornir-automation/nornir#338]
Hi, any ideas on what may be causing this issue, please see below for errors:
sudo pip install nornir
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-Ix0Ad0/pydantic/
pip --no-cache-dir install nornir
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-hn0RAU/pydantic/
Regards, mk

**Comment by dbarrosop** [comment]
Just tested on ubuntu 18.04 myself and worked fine. Which ubuntu version? Try updating `pip` first and pasting the entire output if it doesn't work (please, make sure you format the message properly).

**Comment by mkazam** [comment]
[nornir1.txt](https://github.com/nornir-automation/nornir/files/2930837/nornir1.txt)
kabir@ecl-vm-kabir:~$ lsb_release -d
Description:    Ubuntu 18.10
Just a word of note, I'm from a networking background & new to linux. I'm learning it as it's beneficial for the network automation tools.
Regards, mk

**Comment by mkazam** [comment]
kabir@ecl-vm-kabir:~$ pip --version
pip 9.0.1 from /usr/lib/python2.7/dist-packages (python 2.7)

**Comment by dmfigol** [comment]
We are currently supporting only Python 3.6.2+
Try: `python3.6 -m pip install --user nornir`

**Comment by dbarrosop** [comment]
Closing this issue.
