### ISSUE TITLE
Fix docs to reflect that only Python 3.6.2+ is supported

### ISSUE THREAD

**Issue by dmfigol** [nornir-automation/nornir#339]
On Python 3.6.1 `nornir` import crashes with the following:
```
Traceback (most recent call last):
  File "test-nornir-01.py", line 3, in <module>
    from nornir.core import InitNornir
  File ".../lib/python3.6/site-packages/nornir/__init__.py", line 1, in <module>
    from nornir.init_nornir import InitNornir
  File ".../lib/python3.6/site-packages/nornir/init_nornir.py", line 4, in <module>
    from nornir.core.connections import Connections
  File ".../lib/python3.6/site-packages/nornir/core/connections.py", line 2, in <module>
    from typing import Any, Dict, NoReturn, Optional, Type
ImportError: cannot import name 'NoReturn'
```

**Comment by IDQDD** [comment]
on python 3.5.2 (default for ubuntu 16.04) nornir is being installed successfully 
but then crushes on **import nornir.core**
```bash
$ python3
Python 3.5.2 (default, Oct  8 2019, 13:06:37) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import nornir.core
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/nornir/__init__.py", line 1, in <module>
    from nornir.init_nornir import InitNornir
  File "/usr/local/lib/python3.5/dist-packages/nornir/init_nornir.py", line 19
    return f"{cls.__module__}.{cls.__name__}"
                                            ^
SyntaxError: invalid syntax
```
this is because the python version < 3.6 doesn't support fstrings
please add this to your documentation

thx

**Comment by nashJH27** [comment]
I am facing the same issue with nornir and python 3.5.2. Is there a workaround for this in place?

**Comment by dmfigol** [comment]
@nashJH27 nornir is supported only since 3.6.2.
3.5.2 will not work.

**Comment by sergun4ik** [comment]
I have got the same issue on Python 3.6.8

**Comment by dmfigol** [comment]
@sergun4ik please provide the traceback and show your python version in the outputs.

**Comment by sergun4ik** [comment]
@dmfigol Sure, here you go.

`root@4f3ef8e59b29:/# python3 -V
Python 3.6.8
root@4f3ef8e59b29:/# python3
Python 3.6.8 (default, Dec 25 2018, 00:00:00)
[GCC 4.8.4] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import nornir
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/nornir/__init__.py", line 3, in <module>
    from nornir.init_nornir import InitNornir
  File "/usr/local/lib/python3.6/site-packages/nornir/init_nornir.py", line 4, in <module>
    from nornir.core import Nornir
  File "/usr/local/lib/python3.6/site-packages/nornir/core/__init__.py", line 7, in <module>
    from nornir.core.inventory import Inventory
  File "/usr/local/lib/python3.6/site-packages/nornir/core/inventory.py", line 7, in <module>
    from nornir.core.connections import ConnectionPlugin, Connections
  File "/usr/local/lib/python3.6/site-packages/nornir/core/connections.py", line 2, in <module>
    from typing import Any, Dict, NoReturn, Optional, Type
ImportError: cannot import name 'NoReturn'`

**Comment by dmfigol** [comment]
@sergun4ik I can't reproduce this:
```
-> % docker run -it --rm python:3.6.8-slim-stretch bash
root@392d44e513e0:/# pip install nornir
Collecting nornir
...
Successfully installed MarkupSafe-1.1.1 PyYAML-5.3 bcrypt-3.1.7 certifi-2019.11.28 cffi-1.13.2 chardet-3.0.4 ciscoconfparse-1.4.11 colorama-0.4.3 cryptography-2.8 dataclasses-0.7 dnspython-1.16.0 future-0.18.2 idna-2.8 jinja2-2.11.1 junos-eznc-2.3.1 lxml-4.5.0 mypy-extensions-0.4.3 napalm-2.5.0 ncclient-0.6.7 netaddr-0.7.19 netmiko-2.4.2 nornir-2.3.0 nxapi-plumbing-0.5.2 paramiko-2.7.1 passlib-1.7.2 pyIOSXR-0.53 pycparser-2.19 pydantic-0.18.2 pyeapi-0.8.3 pynacl-1.3.0 pyparsing-2.4.6 pyserial-3.4 requests-2.22.0 ruamel.yaml-0.15.100 scp-0.13.2 six-1.14.0 textfsm-1.1.0 transitions-0.7.2 typing-extensions-3.7.4.1 urllib3-1.25.8 yamlordereddictloader-0.4.0
root@392d44e513e0:/# python
Python 3.6.8 (default, Jun 11 2019, 01:21:42)
[GCC 6.3.0 20170516] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import nornir
>>> from nornir.init_nornir import InitNornir
>>> from typing import NoReturn
>>>
```

Could you please provide exact steps to reproduce this?
Were there any attempts to upgrade python from older to newer version?
Do you see this in docker? What's the base image?

This issue should not appear in python 3.6.2+. Typing is a standard module and `NoReturn` is an attribute there: https://docs.python.org/3.6/library/typing.html#typing.NoReturn (docs says it's 3.6.5+ but I just confirmed that it is 3.6.2+)
If `typing.NoReturn` is not there on 3.6.8 it indicates some problem with python installation.

**Comment by sergun4ik** [comment]
@dmfigol 
The base docker image is tutum/ubuntu, which originally came with Python3.4, so I have manually installed 3.6.8 using apt first and then tried downloading source and make installing it. 

I have tried to use the docker base image you are using and it works just fine, so I can live with that :) thanks for your swift response.

**Comment by dbarrosop** [comment]
I am closing this one due to age. If someone wants to update the docs feel free to open a PR.

**Comment by sindhujit1** [comment]
I am facing this issue in my windows M/C. Using python 3.6.1. Works fine in linux.

**Comment by ktbyers** [comment]
@sindhujit1 Nornir requires Python 3.6.2+.
