### ISSUE TITLE
Print OrderDicts nicely in print_result()

### ISSUE THREAD

**Issue by wdesmedt** [nornir-automation/nornir#341]
Currently, collections.OrderedDict's are printed as-is in a very unpretty fashion. When working with `ncclient` and `xmltodict`, the latter deserializes XML into nested OrderedDicts. 
Suggestion is to check type of result against OrderedDict and use json.dumps to print result nicely.

I can issue a PR if you want.

**Comment by dbarrosop** [comment]
> Suggestion is to check type of result against OrderedDict and use json.dumps to print result nicely.

yes, I think replacing pprint with json.dumps is a good idea.

 > I can issue a PR if you want.

please :D
