### ISSUE TITLE
nornir basics

### ISSUE THREAD

**Issue by mkazam** [nornir-automation/nornir#343]
I think issue #338 was resolved but I now have the following issue:
Thank you so much Dmitry
[nornir1.txt](https://github.com/nornir-automation/nornir/files/2935738/nornir1.txt)
!
I'm following the instruction on readthedocs & using the example by Stuart Clark but I get the below error when try to run the code:
Does the below confirm that nornir is installed - as pip freeze | grep nornir returned nothing.
kabir@ecl-vm-kabir:~$ python3.6
Python 3.6.7 (default, Oct 22 2018, 11:32:17) 
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import nornir.core
>>> quit()
kabir@ecl-vm-kabir:~$ python3.6 nornir_val_static.py
Traceback (most recent call last):
  File "nornir_val_static.py", line 8, in <module>
    from nornir.core import InitNornir
ImportError: cannot import name 'InitNornir'
Regards, mk

**Comment by mkazam** [comment]
nornir1.txt includes the config for the 3 files - hosts.yml, groups.yml & the python code itself
regards, mk

**Comment by dbarrosop** [comment]
Two comments:

1. please, look into how to format properly comments on github. It's just markdown so it's not too hard :)
2. Your code is not compatible with nornir 2.0, I'd suggest looking into the official tutorial: https://nornir.readthedocs.io/en/stable/tutorials/intro/index.html

I am closing the issue as there are no actionable items but feel free to keep commenting and asking questions.
