### ISSUE TITLE
nornir - convert few lines of v1 to v2 

### ISSUE THREAD

**Issue by mkazam** [nornir-automation/nornir#344]
So, this is proving harder than I anticipated :)
I've managed to run tests with most of the automation tools out there in the last 2-3 months - nornir is the last one - whilst trying to learn linux, python & the etiquttes of github :)
On that note, is anyone able to convert the attached few lines of code from version 1 to 2?
I understand this may not be a usual request but not sure where else to go for help.
If so, it would be greatly appreciated!
Regards, mk, network engineer
[nornir2.txt](https://github.com/nornir-automation/nornir/files/2935928/nornir2.txt)

**Comment by dmfigol** [comment]
https://nornir.readthedocs.io/en/stable/upgrading/1_to_2.html
import should be changed from `from nornir.core import InitNornir` to `from nornir import InitNornir`
Ideally, you would also want to provide `config.yaml` as well. It is shown in the docs tutorial.

**Comment by mkazam** [comment]
Thank you Dmitry, just watching your you tube Network programmability stream 17 :)
You may close the case, I think I will return when I learn some more about Nornir.
Regards, mk

**Comment by mkazam** [comment]
.
