### ISSUE TITLE
Path to files in `config.yaml` depends on the working directory

### ISSUE THREAD

**Issue by dmfigol** [nornir-automation/nornir#346]
Personally, I find it confusing that when you specify paths to `host_file`, `group_file` in `config.yaml` they are treated as relative path from the script execution directory, instead of relative to `config.yaml` itself.
What do you think?

**Comment by dbarrosop** [comment]
Paths are always relative to the working dir. if you find it confusing use absolute paths :D Something we can do though is expand env variables so you can do something like:

```
hosts_file: $MY_CUSTOM_ENV/inventory/hosts.yaml
```

**Comment by dmfigol** [comment]
When it is Python code, it is easy to hack something like `Path(__file__).parent / "inventory/hosts.yaml"`, but with a config file `config.yaml` it is harder to do: either you use absolute paths (which make it problematic to port between dev / prod), or you always need to be extra careful where you call the script.
May be I am just imagining a problem which does not exist.
That said I like the idea of automatic env vars expansion and it is really easy to implement.

**Comment by dmfigol** [comment]
I will close this, not really relevant anymore. though env var expand is still an interesting feature.
