### ISSUE TITLE
Allow Inventory Data To be Passed From A Dictionary

### ISSUE THREAD

**Issue by ipv6freely** [nornir-automation/nornir#347]
It would be really helpful to be able to pass inventory information from a (correctly structured) host and groups dictionary. How the dictionary was generated should be irrelevant. 

In my particular use case, I'm building the host dictionary simply based on a list of hosts from an NMS or a manual list of IPs. 

In prior versions of Nornir, the following worked correctly:
```isisdb = ['192.168.1.1', '192.168.1.2', '192.168.1.3']

hosts = {
    router: {
        'ip': router,
        'groups': ['wan-routers'],
        'role': 'wan-router'
    } for router in isisdb
}

groups = {
    'wan-routers': {
        'nornir_nos': 'junos'
    }
}

inv = Inventory(hosts=hosts, groups=groups)
```

This doesn't seem to work even more, even when the dictionaries are formatted correctly with correct keys. Restoring this function would be really nice to be able to build an inventory from any user-generated and correctly structured data.

**Comment by dbarrosop** [comment]
I think this is fixed now so I am closing this issue. Feel free to reopen otherwise.
