### ISSUE TITLE
save_config() got an unexpected keyword argument 'confirm_response'

### ISSUE THREAD

**Issue by senses0** [nornir-automation/nornir#352]
Hi,

I am running this code against a test device, where it logs into the device and attempts to save the configuration

```
from nornir import InitNornir
from nornir.plugins.tasks.networking import netmiko_save_config
from nornir.plugins.functions.text import print_result

def save_config(task):
    task.run(task=netmiko_save_config,
             name='Saving configuration',
             cmd='copy running-config startup-config')

result = target_hosts.run(save_config)
print_result(result, vars=["stdout"])
```

However Nornir throws an exception and I get below message
"save_config() got an unexpected keyword argument 'confirm_response'".

What's more strange is, despite the exception, device configuration is saved to startup-config file.

**Comment by enzzzy** [comment]
Looks like the netmiko CiscoIosSSH driver does not have confirm_response defined as an argument for the save_config method.
@ktbyers in #271 you asked me to add confirm_response as an argument for the netmiko_save_config task. Looks like not all netmiko drivers accept that argument for the save_config method.
https://github.com/ktbyers/netmiko/blob/ac6e944880cc156ceba63de83dc8c1751ad23239/netmiko/cisco/cisco_ios.py#L35
Should I change the behavior and not pass confirm_response to the netmiko save_config method if it is not explicitly defined as an argument for the nornir task?

**Comment by ktbyers** [comment]
That is probably a bug in Netmiko. It should probably be fixed in Netmiko (i.e. all Netmiko drivers should accept the same set of arguments for that method).

**Comment by ctopher78** [comment]
@ktbyers - Is someone already working on this?  I'm not seeing an open issue/PR in the Netmiko repo.  I'm happy to take a crack at it, but I just want to make sure I'm not duplicating effort.

**Comment by ktbyers** [comment]
@carlniger Did you work on this? I know we talked about it, but not sure if we did anything on it.

**Comment by carlniger** [comment]
I did not, but its bookmarked and this afternoon/next week is looking good to dig into it!

**Comment by ktbyers** [comment]
@ctopher78 @carlniger It is fine either way...so I would just say whoever wants to work on it first/has time--to dive into it.


Regards, Kirk

**Comment by ctopher78** [comment]
I just created the following [Netmiko PR](https://github.com/ktbyers/netmiko/pull/1158) for this.

**Comment by ktbyers** [comment]
This is fixed in the Netmiko `develop` branch. I am going to go ahead and close this.
