### ISSUE TITLE
ValueError: Unable to find prompt:

### ISSUE THREAD

**Issue by TLINDEN** [nornir-automation/nornir#377]
I've got a basic Cisco config (can't post it here) which only consists of a couple interfaces and an acl. I then use this code to configure a device (it's only one right now):

```python
from nornir import InitNornir
from nornir.plugins.functions.text import print_result
from nornir.plugins.tasks import networking, text
import re, yaml, ipaddress

def config_router(task):
    # Transform inventory data to configuration via a template file
    r = task.run(task=text.template_file,
                 name="Router Configuration",
                 template="router.j2",
                 path=(f"templates/{task.host['hwtype']}", f"templates"))

    # Save the compiled configuration into a host variable
    task.host["config"] = r.result

    if True:
        # Deploy that configuration to the device using NAPALM
        task.run(task=networking.napalm_configure,
                 name="Loading Configuration on the device",
                 replace=False,
                 configuration=task.host["config"])

nr = InitNornir(config_file="config.yaml")

routers = nr.filter(site="w81", role="edge")

nr.data.dry_run = False
adjust_flags(routers.inventory)
result = routers.run(task=config_router)
print_result(result)
```

When I execute this, I can see on the router, that nornir logs into the device multiple times and finally issues the configuration commands. When it's done (that is, after the last config command), I see the following message on the router:

```
*Apr 12 15:21:43: %PARSER-4-BADCFG: Unexpected end of configuration file.
*Apr 12 15:21:43: %SYS-5-CONFIG_C: Running-config file is Modified 
*Apr 12 15:21:47: %SYS-6-LOGOUT: User cisco has exited tty session 2(172.18.181.12)
```

And nordir fails with:

```---- Loading Configuration on the device ** changed : False -------------------- ERROR
Traceback (most recent call last):
  File "/home/tl/.local/share/virtualenvs/router-gtV0K0m5/lib/python3.6/site-packages/nornir/core/task.py", line 67, in start
    r = self.task(self, **self.params)
  File "/home/tl/.local/share/virtualenvs/router-gtV0K0m5/lib/python3.6/site-packages/nornir/plugins/tasks/networking/napalm_configure.py", line 37, in napalm_configure
    device.commit_config()
  File "/home/tl/.local/share/virtualenvs/router-gtV0K0m5/lib/python3.6/site-packages/napalm/ios/ios.py", line 526, in commit_config
    output = self._commit_handler(cmd)
  File "/home/tl/.local/share/virtualenvs/router-gtV0K0m5/lib/python3.6/site-packages/napalm/ios/ios.py", line 451, in wrapper
    return f(self, *args, **kwargs)
  File "/home/tl/.local/share/virtualenvs/router-gtV0K0m5/lib/python3.6/site-packages/napalm/ios/ios.py", line 481, in _commit_handler
    self.device.set_base_prompt()
  File "/home/tl/.local/share/virtualenvs/router-gtV0K0m5/lib/python3.6/site-packages/netmiko/base_connection.py", line 1040, in set_base_prompt
    prompt = self.find_prompt(delay_factor=delay_factor)
  File "/home/tl/.local/share/virtualenvs/router-gtV0K0m5/lib/python3.6/site-packages/netmiko/base_connection.py", line 1081, in find_prompt
    raise ValueError("Unable to find prompt: {}".format(prompt))
ValueError: Unable to find prompt: 

^^^^ END config_router ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

Also nornir doesn't check if the configuration is already there, it always pushes the whole config onto the router.

**Comment by dbarrosop** [comment]
> that nornir logs into the device multiple times and finally issues the configuration commands

Can you share the logs?

> ValueError: Unable to find prompt: 

My guess is your configuration is trying to change the prompt or finishing applying the configuration very slowly. If it's the latter you can check napalm's documentation to see how to increase the timer (global_delay_factor or something like that IIRC).

> Also nornir doesn't check if the configuration is already there, it always pushes the whole config onto the router

`napalm_configure` will apply the configuration you pass it to so that's expected.

**Comment by dmfigol** [comment]
I've had that with netmiko. Kirk was helping me out.
What helped is a combination of several things:
* increasing delay factor
* adding expected prompt (however, considering you are using napalm, idk how to integrate that)
* retry helper
```
send_command_retry = utils.retry((NetMikoTimeoutException, OSError))(
    netmiko_send_command
)
prompt = re.escape(host.connections["netmiko"].connection.base_prompt) + "#"
r = task.run(
    send_command_retry,
    command_string=command,
    use_textfsm=True,
    expect_string=prompt,
)
```

**Comment by TLINDEN** [comment]
> Can you share the logs?

```
*Apr 12 15:21:25: %SEC_LOGIN-5-LOGIN_SUCCESS: Login Success [user: cisco] [Source: 172.20.131.12] [localport: 22] at 15:21:25 UTC Fri Apr 12 2019
*Apr 12 15:21:31: %SEC_LOGIN-5-LOGIN_SUCCESS: Login Success [user: cisco] [Source: 172.20.131.12] [localport: 22] at 15:21:31 UTC Fri Apr 12 2019
*Apr 12 15:21:34: %PARSER-5-CFGLOG_LOGGEDCMD: User:cisco  logged command:file prompt quiet 
*Apr 12 15:21:37: %SYS-5-CONFIG_I: Configured from console by cisco on vty1 (172.20.131.12)
*Apr 12 15:21:40: %PARSER-5-CFGLOG_LOGGEDCMD: User:cisco  logged command:service timestamps log datetime localtime 
*Apr 12 15:21:40: %PARSER-5-CFGLOG_LOGGEDCMD: User:cisco  logged command:logging queue-limit 100
*Apr 12 15:21:40: %PARSER-5-CFGLOG_LOGGEDCMD: User:cisco  logged command:logging buffered 20000
*Apr 12 15:21:40: %PARSER-5-CFGLOG_LOGGEDCMD: User:cisco  logged command:login on-failure log 
*Apr 12 15:21:40: %PARSER-5-CFGLOG_LOGGEDCMD: User:cisco  logged command:login on-success log 
*Apr 12 15:21:40: %PARSER-5-CFGLOG_LOGGEDCMD: User:cisco  logged command:logging alarm informational 
*Apr 12 15:21:40: %PARSER-5-CFGLOG_LOGGEDCMD: User:cisco  logged command:logging source-interface Loopback1 
*Apr 12 15:21:40: %PARSER-5-CFGLOG_LOGGEDCMD: User:cisco  logged command:logging host 172.16.144.16
*Apr 12 15:21:40: %PARSER-5-CFGLOG_LOGGEDCMD: User:cisco  logged command:ntp source GigabitEthernet1 
*Apr 12 15:21:40: %PARSER-5-CFGLOG_LOGGEDCMD: User:cisco  logged command:ntp server 172.20.143.14
*Apr 12 15:21:40: %PARSER-5-CFGLOG_LOGGEDCMD: User:cisco  logged command:ntp server 172.20.230.7
*Apr 12 15:21:40: %PARSER-5-CFGLOG_LOGGEDCMD: User:cisco  logged command:ntp server 172.27.200.7
*Apr 12 15:21:40: %PARSER-5-CFGLOG_LOGGEDCMD: User:cisco  logged command:ntp server 172.20.191.7
*Apr 12 15:21:40: %PARSER-5-CFGLOG_LOGGEDCMD: User:cisco  logged command:interface Loopback0 
*Apr 12 15:21:40: %PARSER-5-CFGLOG_LOGGEDCMD: User:cisco  logged command:description internal loopback for BGP sessions
*Apr 12 15:21:40: %PARSER-5-CFGLOG_LOGGEDCMD: User:cisco  logged command:ip address 192.168.160.98 255.255.255.255 
*Apr 12 15:21:40: %PARSER-5-CFGLOG_LOGGEDCMD: User:cisco  logged command:no shutdown 
*Apr 12 15:21:43: %PARSER-4-BADCFG: Unexpected end of configuration file.
*Apr 12 15:21:43: %SYS-5-CONFIG_C: Running-config file is Modified 
*Apr 12 15:21:47: %SYS-6-LOGOUT: User cisco has exited tty session 2(172.20.131.12)
```
> My guess is your configuration is trying to change the prompt

Nope.

> or finishing applying the configuration very slowly. If it's the latter you can check napalm's documentation to see how to increase the timer (global_delay_factor or something like that IIRC).

Well, I'm using a Nornir interface and I don't have a napalm instance accessible directly. In fact, the napalm docs say:

> NAPALM supports passing certain optional arguments to some drivers. To do that you have to pass a dictionary via the optional_args parameter when creating the object

So, this has to be done somewhere in Nornir or it must provide a way for the user to pass options somehow. Here's the definition of `napalm_configure` in `nornir/plugins/tasks/networking/napalm_configure.py`:
```python
def napalm_configure(
    task: Task,
    dry_run: Optional[bool] = None,
    filename: Optional[str] = None,
    configuration: Optional[str] = None,
    replace: bool = False,
) -> Result:
```

There's no tunable or dict or whatever being passed to napalm available to me by the looks of it.

> `napalm_configure` will apply the configuration you pass it to so that's expected.

The documentation on https://nornir.readthedocs.io/en/stable/tutorials/intro/grouping_tasks.html says otherwise. I have the parameter `replace` set to `False` and Nornir should call `load_merge_candidate()` in this case:

```python
    if replace:
        device.load_replace_candidate(filename=filename, config=configuration)
    else:
        device.load_merge_candidate(filename=filename, config=configuration)
    diff = device.compare_config()
```

It should show a diff after execution and after a second run it should change nothing.

**Comment by TLINDEN** [comment]
PS: `global_delay_factor` doesn't help. I tried it directly via commandline:
```shell
napalm --debug --user cisco --password cisco --vendor ios --optional_args "port=22, global_delay_factor=60" 172.16.1.79 configure router.cfg --strategy merge
```
Traceback (most recent call last):
  File "/home/tl/.local/share/virtualenvs/router-gtV0K0m5/bin/napalm", line 10, in <module>
    sys.exit(main())
  File "/home/tl/.local/share/virtualenvs/router-gtV0K0m5/lib/python3.6/site-packages/napalm/base/clitools/cl_napalm.py", line 309, in main
    run_tests(args)
  File "/home/tl/.local/share/virtualenvs/router-gtV0K0m5/lib/python3.6/site-packages/napalm/base/clitools/cl_napalm.py", line 294, in run_tests
    configuration_change(device, args.config_file, args.strategy, args.dry_run)
  File "/home/tl/.local/share/virtualenvs/router-gtV0K0m5/lib/python3.6/site-packages/napalm/base/clitools/cl_napalm.py", line 245, in configuration_change
    call_commit_config(device)
  File "/home/tl/.local/share/virtualenvs/router-gtV0K0m5/lib/python3.6/site-packages/napalm/base/clitools/cl_napalm.py", line 31, in wrapper
    r = func(*args, **kwargs)
  File "/home/tl/.local/share/virtualenvs/router-gtV0K0m5/lib/python3.6/site-packages/napalm/base/clitools/cl_napalm.py", line 231, in call_commit_config
    return device.commit_config(*args, **kwargs)
  File "/home/tl/.local/share/virtualenvs/router-gtV0K0m5/lib/python3.6/site-packages/napalm/ios/ios.py", line 526, in commit_config
    output = self._commit_handler(cmd)
  File "/home/tl/.local/share/virtualenvs/router-gtV0K0m5/lib/python3.6/site-packages/napalm/ios/ios.py", line 451, in wrapper
    return f(self, *args, **kwargs)
  File "/home/tl/.local/share/virtualenvs/router-gtV0K0m5/lib/python3.6/site-packages/napalm/ios/ios.py", line 481, in _commit_handler
    self.device.set_base_prompt()
  File "/home/tl/.local/share/virtualenvs/router-gtV0K0m5/lib/python3.6/site-packages/netmiko/base_connection.py", line 1040, in set_base_prompt
    prompt = self.find_prompt(delay_factor=delay_factor)
  File "/home/tl/.local/share/virtualenvs/router-gtV0K0m5/lib/python3.6/site-packages/netmiko/base_connection.py", line 1081, in find_prompt
    raise ValueError("Unable to find prompt: {}".format(prompt))
ValueError: Unable to find prompt: 
```

**Comment by TLINDEN** [comment]
Ok, found the culprit: as mentioned I configure several interfaces, one if which is a DHCP interface and upon re-configuring it emits such a message:

```
*Apr 15 09:17:54: %DHCP-6-ADDRESS_ASSIGN: Interface GigabitEthernet6 assigned DHCP address 172.16.1.79, mask 255.255.255.0, hostname bb211
```

As it seems the messages can be seen by napalm and of course it doesn't match the prompt (`$hostname#`) hence the failure.

So, when I remove the config snippet for this interface (or just remove the dhcp line), everything runs as expected.

Now, the fix would be to disable those messages, but somehow I seem to be unable to do that, whatever I configure, the Router logs the DHCP message anyway.

Any ideas?

**Comment by TLINDEN** [comment]
Nope, I added this to my cisco config: `no logging monitor` and after this I don't see any such messages anymore on the VTY. However, Nordir (and napalm) still dies because of a lost prompt.

**Comment by dbarrosop** [comment]
This is an issue you should probably raise directly in the napalm repo, there isn't much we can do here to be honest.

I am going to be closing the issue but feel free to reopen if you think there is anything we should address.
