### ISSUE TITLE
Napalm Getter "environment" broken

### ISSUE THREAD

**Issue by LongBeachHXC** [nornir-automation/nornir#391]
Hey Nornir team,

It appears that the Napalm getter for "environment" is broken. The received error message does not appear to be from my local environment but I could be wrong. Just wanted to bring this to your attention.

>>> test_cmd = nr.run(task=networking.napalm_get, getters=["environment"])
>>>
>>> print_result(test_cmd)
napalm_get**********************************************************************
* US-TOP-MDF-AS1 ** changed : False ********************************************
vvvv napalm_get ** changed : False vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv ERROR
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/nornir/core/task.py", line 67, in start
    r = self.task(self, **self.params)
  File "/usr/local/lib/python3.6/dist-packages/nornir/plugins/tasks/networking/napalm_get.py", line 61, in napalm_get
    result[g] = method(**options)
  File "/usr/local/lib/python3.6/dist-packages/napalm/ios/ios.py", line 1860, in get_environment
    total_mem = int(proc_total_mem) + int(io_total_mem)
UnboundLocalError: local variable 'proc_total_mem' referenced before assignment

^^^^ END napalm_get ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

**Comment by ktbyers** [comment]
@LongBeachHXC Can you re-file this issue against napalm--that is where the problem needs fixed.


Regards,

Kirk
