### ISSUE TITLE
Prompting for credentials - Not storing in plain text

### ISSUE THREAD

**Issue by thetechuser** [nornir-automation/nornir#397]
Hello! Is there a known way to have scripts, using nornir, prompt for password to avoid storing it in plain-text in yaml files? I also want to stay away from storing the password in an environment variable.

**Comment by ktbyers** [comment]
@thetechuser I use this some times:

https://github.com/ktbyers/nornir_test/blob/master/nornir_test/nornir_utilities.py#L5

Also I think the Nornir docs have a transform function example that does this.

**Comment by jgeromero** [comment]
> 

Hi @ktbyers, kind of an old thread but is the nornir_utilities.py still a good method to use now days or something better exists? Also, the function expects an argument norn.. where do I get this from? Ty

**Comment by ktbyers** [comment]
@jgeromero I would just loop over the hosts in inventory or use a transform function. This should show you both patterns:

https://github.com/twin-bridges/nornir_course/tree/master/bonus1/collateral/transform_function/simple

**Comment by jgeromero** [comment]
@ktbyers thank you, I ended up using a transform_function as suggested but for some reason is giving me the following: 
nornir.core.exceptions.PluginNotRegistered: plugin 'transform_func' is not registered
Here's my code, not sure what I missed: https://bpa.st/RL6Q

**Comment by ubaumann** [comment]
There is a transform_function in nornir_utils https://github.com/nornir-automation/nornir_utils/blob/master/nornir_utils/plugins/inventory/transform_functions.py

**Comment by jgeromero** [comment]
@ubaumann do you have an example of how to use it, where do I call the load_credentials function? Also, what param do I use to run it for all hosts or a specific group? 

Just as a side note the version of the package pip has is from Feb 2021 so I had to upgrade to get the latest , thank you!

**Comment by ubaumann** [comment]
https://github.com/nornir-automation/nornir_utils/blob/master/docs/source/tutorials/load_credentials.ipynb

**Comment by ubaumann** [comment]
Think the load_credentials function is not released but you can learn from the code or install the develop branch.

**Comment by jgeromero** [comment]
Works as expected, thanks for adding this functionality!

**Comment by jgeromero** [comment]
@ubaumann forgot to ask, any future plans on extending this to things like enable/secret passwords within optional_args?

**Comment by ktbyers** [comment]
@jgeromero Your earlier issue with `nornir.core.exceptions.PluginNotRegistered: plugin 'transform_func' is not registered` was likely due to calling InitNornir before you executed this `TransformFunctionRegister.register`.

Or worded differently, your InitNornir() call must come after the "TransformFunctionRegister".

**Comment by jgeromero** [comment]
> @jgeromero Your earlier issue with `nornir.core.exceptions.PluginNotRegistered: plugin 'transform_func' is not registered` was likely due to calling InitNornir before you executed this `TransformFunctionRegister.register`.
> 
> Or worded differently, your InitNornir() call must come after the "TransformFunctionRegister".

Ah that's what probably happened since I was calling it before "TransformFunctionRegister" I've decided to use the transform_function in nornir_utils for now. Thank you
