### ISSUE TITLE
Does Nornir support Cisco switches IOS version 12.2(58)SE2?

### ISSUE THREAD

**Issue by thetechuser** [nornir-automation/nornir#400]
Getting this "% Invalid input detected at '^' marker." when sending "write memory" command to some switches using Nornir (2.2.0).

**Comment by ktbyers** [comment]
This `% Invalid input detected at '^' marker.` is from the switch.

Are you in enable mode?

**Comment by dbarrosop** [comment]
Yes, it’s supported both via napalm and netmiko. If you have issues we’d suggest you to head to either slack or discourse and share your code and traceback there so people can help out.

Here are the details on how to join slack/discourse: https://github.com/nornir-automation/nornir#contact--support

Closing this issue as we use this system to track bugs in the software but don't hesitate to join us either in slack or discourse :)

**Comment by thetechuser** [comment]
It is a mode issue, indeed @ktbyers. I will see what's wrong with my groups and hosts files. Thanks!! @dbarrosop Thanks!
