### ISSUE TITLE
Cisco IOS devices do not enter enable mode

### ISSUE THREAD

**Issue by jcox-dev-99** [nornir-automation/nornir#401]
Alright, so I'm using SimpleInventory, and I created config/hosts/groups files.  I'm able to connect to devices, run show commands, etc.  When I try to enter a config command, I fail when entering enable mode.  

![image](https://user-images.githubusercontent.com/30243565/58510129-b4fe0a00-815d-11e9-8f68-3dbe00ff7bbc.png)

![image](https://user-images.githubusercontent.com/30243565/58510151-bf200880-815d-11e9-92b2-49996b049f3a.png)

I have tried passing the extras:  secret:  xxxxx parameter in both hosts and groups, in the following format:

![image](https://user-images.githubusercontent.com/30243565/58510790-1d012000-815f-11e9-9e57-c616b6485c24.png)

Let me know if you see something glaring, I'm sure I have an error in the yaml but this is the only format I could pass without an error.

Thanks in advance.

**Comment by ktbyers** [comment]
See:

https://nornir.discourse.group/t/passing-enable-secret/16

But should be `connection_options > netmiko` and NOT `additionalProperties`
