### ISSUE TITLE
ssl_verify in netbox plugin should accept string

### ISSUE THREAD

**Issue by pstanczak-eg** [nornir-automation/nornir#406]
Currently `nornir/plugins/inventory/netbox.py ` uses `ssl_verify: bool = True` used by `session.verify = ssl_verify` in `class NBInventory`.

The issue is when you need to specify certificate for valid SSL certification.  The variable only accepts **bool**, where **str** needs to be passed with the '/path/to/certfile'.

https://2.python-requests.org//en/master/user/advanced/#ssl-cert-verification

> You can pass verify the path to a CA_BUNDLE file or directory with certificates of trusted CAs:

`>>> requests.get('https://url.com', verify='/path/to/certfile')`

**Comment by dbarrosop** [comment]
Thanks for raising this issue. Two comments:

  1. For reference as you probably know already, the type in the signature is for documentation/linting purposes, you can pass the string if you want to.
  2. Would you mind sending a PR correcting it?

**Comment by dmfigol** [comment]
Fixed with #434
