### ISSUE TITLE
Plans for a REST API ?

### ISSUE THREAD

**Issue by mayuresh82** [nornir-automation/nornir#409]
Are there any plans to introduce a REST API so tasks can be run remotely ? One of the most useful and powerful features of ansible tower / AWX is the rest API that allows to execute playbooks remotely. IMO it would be an excellent addition that would also help drive adoption.

**Comment by dbarrosop** [comment]
No, currently my recommendation is to use [stackstorm](https://stackstorm.com/). You will get, not only the API you want, but also the ability to do chatops, trigger things based on events, sensors, etc...

**Comment by dbarrosop** [comment]
In any case, if people is only interested in running scripts via an API we could certainly look into building something simpler to deploy than st2 that can do that.

**Comment by dbarrosop** [comment]
Also, is this something people would want as an paid feature or is the expectation this would be another opensource/free_as_a_beer project?

**Comment by mayuresh82** [comment]
Stackstorm is more of an event based system. I dont think the comparison is valid.  A REST API interface to nornir would allow us to execute tasks remotely and would make nornir available as a (micro) service.  
Re: paid vs free, not sure if we should follow the example of Ansible tower. Unless you have plans to convert Nornir into an LLC :)

**Comment by ktbyers** [comment]
Closing...not really an issue.

As always with open-source anyone is welcome to build the things they want themselves.
