### ISSUE TITLE
Local variable 'yml' referenced before assignment 

### ISSUE THREAD

**Issue by simonacorinapop** [nornir-automation/nornir#411]
Hi, 

I am getting the following error when initialising nornir with a custom hosts dictionary, instead of using the hosts.yaml file for the SimpleInventory plugin.

```
    nr = InitNornir(
        core={"num_workers": 10},
        inventory={
            "plugin": "nornir.plugins.inventory.simple.SimpleInventory",
            "options": {
                "hosts": {rows['HOSTNAME']: {'hostname': rows['IP']} for rows in csv.DictReader(open(HOSTS_FILE), delimiter=",")},
                "group_file": "inventory/groups.yaml",
                "defaults_file": "inventory/defaults.yaml",
            }
        }
    )
```

Traceback (most recent call last):
  File "C:/Users/myuser/PycharmProjects/python3/ios-upgrade/test.py", line 130, in <module>
    main()
  File "C:/Users/myuser/PycharmProjects/python3/ios-upgrade/test.py", line 68, in main
    init_data_structures()
  File "C:/Users/myuser/PycharmProjects/python3/ios-upgrade/test.py", line 61, in init_data_structures
    "defaults_file": "inventory/defaults.yaml",
  File "C:\Python37\lib\site-packages\nornir\init_nornir.py", line 76, in InitNornir
    **conf.inventory.options,
  File "C:\Python37\lib\site-packages\nornir\core\deserializer\inventory.py", line 129, in deserialize
    deserialized = cls(*args, **kwargs)
  File "C:\Python37\lib\site-packages\nornir\plugins\inventory\simple.py", line 40, in __init__
    groups = yml.load(f) or {}
UnboundLocalError: local variable 'yml' referenced before assignment

Can you please fix? As a workaround I have locally modified the simply.py file by taking the yml  declaration outside the if statement. 

Thank you!

```
class SimpleInventory(Inventory):
    def __init__(
        self,
        host_file: str = "hosts.yaml",
        group_file: str = "groups.yaml",
        defaults_file: str = "defaults.yaml",
        hosts: Optional[HostsDict] = None,
        groups: Optional[GroupsDict] = None,
        defaults: Optional[VarsDict] = None,
        *args: Any,
        **kwargs: Any
    ) -> None:
       yml = ruamel.yaml.YAML(typ="safe")
        if hosts is None:
            with open(host_file, "r") as f:
                hosts = yml.load(f)
...
```

**Comment by dbarrosop** [comment]
Hello,
thanks for reporting this. Your fix is good, would you mind opening a PR?

Regards!
David

**Comment by simonacorinapop** [comment]
Hi David,

Do you mean a pull request? I will try - never done one before.

Cheers,
Simona

**Comment by dbarrosop** [comment]
Exactly. Mostly want to make sure credit goes where it's due ;) but if you can't do it I certainly can do it myself.
