### ISSUE TITLE
Reference Environment Variable for User / Pass

### ISSUE THREAD

**Issue by jas2061461** [nornir-automation/nornir#415]
What is the best way for me to reference an environmental variable for a username and password?

**Comment by ktbyers** [comment]
@jas2061461 This question is more appropriate the discourse group: can you re-ask it there?

https://nornir.discourse.group/

**Comment by jas2061461** [comment]
I created an account this morning on Nornir and made a post.  Unfortunately, I am still unable to post until someone approves my account.  Very frustrating.  Why did you guys lock down your public forum?

**Comment by ktbyers** [comment]
Probably to prevent spam and other issues that can happen with just open forums.

**Comment by dbarrosop** [comment]
>  Why did you guys lock down your public forum?

It is not locked down, anyone can register and there is no approval mechanism. I see a user `jas2061461` in the admin panel marked as active, I guess that's you. Did you register via email? In that case you might have tried to post before validating your account (link in the confirmation email). Can you try again and see if it works? If it doesn't feel free to reach out to me directly (I am on networktocode's slack) with a screenshot of the error you are getting so I can try to help out. There is certainly no manual approval process and nothing indicates the mentioned account has any issue.

**Comment by dbarrosop** [comment]
Just realized you manged to post already. @ktbyers did you do something to fix the situation? If yes, please, reach out to me in private so we can look at it so this doesn't happen again.
