### ISSUE TITLE
Best practices to handle errors

### ISSUE THREAD

**Issue by gmoisio** [nornir-automation/nornir#423]
Hi all, when we can connect to all devices but some task does not apply correctly on a device, we can handle the error and have the devices list onto which there was an issue:
```
try:
    result = nr.run(
        napalm_get,
        getters=['get_facts']
    )
    print_result(result)

except NornirExecutionError:
    print('{0}Issue on: {1}'.
        format(Fore.RED, nr.data.failed_hosts))
```

But what if we cannot connect on a device?
Is there a nice way to have the devices list onto which connection was impossible?

Thanks
Regards

**Comment by ktbyers** [comment]
@gmoisio This question is better suited for our Discourse forum. Can you post this question there?

https://nornir.discourse.group/


Kirk

**Comment by jbl241987** [comment]
The above group link not working now, is there any answer to this question?

But what if we cannot connect on a device?
Is there a nice way to have the devices list onto which connection was impossible?
