### ISSUE TITLE
KeyError when setting a "False" Data value in defaults.yaml

### ISSUE THREAD

**Issue by aSauerwein** [nornir-automation/nornir#429]
Example:
defaults.yaml:
```
---
data:
    key3: value3
    key4: false
```
Python code: 
```
for host, host_obj in nr.inventory.hosts.items():
    print(f'{host}: {host_obj["key3"]}')
    print(f'{host}: {host_obj["key4"]}')
```

host_obj["key4"] will fail with "KeyError"

the reason for this is in inventory.py line 161:
https://github.com/nornir-automation/nornir/blob/develop/nornir/core/inventory.py
```
r = self.defaults.data.get(item)
    if r:
        return r
```
self.defaults.data.get(**KEY4**) = False
and therefore "if r" resolves to False => KeyError. 

potential fix:
```
if r != None:
    return r
```

**Comment by dbarrosop** [comment]
Closed via #443
