### ISSUE TITLE
netmiko_file_transfer module feature request!

### ISSUE THREAD

**Issue by sindhujit** [nornir-automation/nornir#432]
In Netmiko_file_transfer method, there is no way to specify source file as a remote file as opposed to something stored locally. This can reduce the time of deployment for large NXOS images from an FTP server rather than doing it from a VM.

**Comment by ktbyers** [comment]
@sindhujit Not sure I follow you?

netmiko_file_transfer is always Secure Copy and it is always from the control server to the remote network device (assuming "put") or from the remote network device to the control server (assuming "get").

You can transfer files in other ways using netmiko_send_command or some other custom task (i.e. you can initial transfers from the network device, it just isn't using this netmiko_file_transfer module).

**Comment by sindhujit** [comment]
The thing is I am doing the deployment from our automation portal hosted on a VM. My process right now is :- Copy Image from FTP server -> automation portal , then automation portal -> NXOS switch.
It would be better if I could directly copy the file from the FTP server -> NXOS switch through NorNir as that would significantly reduce the time. Is that possible though netmiko_send_command?

**Comment by ktbyers** [comment]
Yes, should be able to do that.
