### ISSUE TITLE
cisco ios / show ip interface brief parser

### ISSUE THREAD

**Issue by a1exigna** [nornir-automation/nornir#453]
Hello Team,

when "exec prompt timestamp" is used on the Cisco IOS boxes
```
line vty 0 15
 exec prompt timestamp
```
parser for task=napalm_get, getters=['facts'] does not work:
```
  ...
File ".local/share/virtualenvs/nornir_1-qORfh3cz/lib/python3.8/site-packages/napalm/ios/ios.py", line 1004, in get_facts
    interface = line.split()[0]
IndexError: list index out of range
```
local fix (am not sure if this should be applied somewhere else)
```
        # show_ip_int_br = re.split(r"Any interface listed with.*", show_ip_int_br)[-1]
        show_ip_int_br = re.split(r"Interface.*", show_ip_int_br)[-1]
```

**Comment by ogenstad** [comment]
I'm closing this as this is an issue with [Napalm](https://github.com/napalm-automation/napalm) where an issue like this should be opened.

I would however urge you to remove the timestamps.
