### ISSUE TITLE
Understanding of add_group() method

### ISSUE THREAD

**Issue by derekcnet** [nornir-automation/nornir#461]
Hi, I'm looking to test out Nornir as an automation platform and I one of the test cases was adding new devices and group definitions to inventory.  So my question on this functionality is two parts.  When I add a group to inventory via the add_group method I see it reflected in the variable but not in the underlying text file which means should the server get rebooted or such the new information will get lost. I guess my question then is this the designed behavior?  Also what is the expected method for more persistent inventory changes? I would expect updating the original inventory file, writing the new host or group via the yaml plugin and then re-initializing the inventory variable, correct?  Appreciate any feedback and if I'm posting on the wrong forum for an operational question let me know and I'll be sure to adjust accordingly and Happy New Year!

**Comment by dbarrosop** [comment]
Hello, I am afraid nornir is not neither a database nor an inventory management system so it won't persist any changes done to the inventory dynamically. If you need that functionality I'd suggest looking into using something like nsot or netbox. As a last resort, you could persist the changes yourself by dumping the inventory into the yaml/json files yourself.

I am closing this as this is not an issue. For support I'd suggest posting in nornir.discourse.group.

Thanks
