### ISSUE TITLE
What Am I doing wrong? Need help 

### ISSUE THREAD

**Issue by pravinrajgit** [nornir-automation/nornir#487]
Hi Krik, 

I'm stuck with Nornir on windows 7, I tried to troubleshoot myself for long and help up.
Would like your help here.

Attaching the error and would like to know what I'm doing wrong.

![er1](https://user-images.githubusercontent.com/58200811/74538453-49193700-4f62-11ea-9b76-4456a4b172c4.PNG)
![er2](https://user-images.githubusercontent.com/58200811/74538454-49193700-4f62-11ea-9d71-720bc2f7ea1a.PNG)

**Comment by dbarrosop** [comment]
Please, refer to slack or the forum for help with your code.

**Comment by dmfigol** [comment]
@pravinrajgit 
The error indicates that file `config.yaml` was not found in the directory where the script is run. 
In python you can check the current directory and its contents using `import os; print(os.getcwd()); print(os.listdir())`
It seems you downloaded the code from our repo and put `config.yaml` there. This is not how Python modules are usually used. The workflow is the following (note, this has nothing to do with Nornir, it's general Python dev workflow):
1) create a directory for your project
2) create virtual environment inside there (or in some other place) and activate it
3) install dependencies that you need using `pip` or similar tools. In your case it would be `pip install nornir`
4) create application files
5) run your application
I'd recommend going through some Python basics tutorial first and then through Nornir tutorials in our docs.
Please note that GitHub issue tracker is for issues, enhancements and features discussions, it's not for troubleshooting user's code. As David noted, the correct place to ask for help would be our slack or forum. Though in this case you need general Python help, not Nornir specific help.

**Comment by pravinrajgit** [comment]
@dmfigol ,


Yes I understand that config.yaml was not found in the directory and I need to know what I'm doing wrong.

No, I haven't  downloaded from repo. I have installed nornir using pip inside my venv.

1) create a directory for your project : Yes I have created a directory for my project.
2) create virtual environment inside there (or in some other place) and activate it : Created venv and activated it inside the venv.
3) install dependencies that you need using pip or similar tools. In your case it would be pip install nornir : had done that.
4) create application files : Trying to run "show version" on select hosts using nornir framework.

Please find below the outputs :
 
Any leads could help.

>>> import os; print(os.getcwd()); print(os.listdir())
C:\Users\TKMAMJA\.PyCharmCE2019.1\venv\Scripts\MyProject
['venv']
>>> nr = InitNornir(core={"num_workers": 50}, config_file="config.yaml")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\TKMAMJA\.PyCharmCE2019.1\venv\Scripts\MyProject\venv\lib\site-packages\nornir\init_nornir.py", line 54,
 in InitNornir
    conf = Config.load_from_file(config_file, **kwargs)
  File "C:\Users\TKMAMJA\.PyCharmCE2019.1\venv\Scripts\MyProject\venv\lib\site-packages\nornir\core\deserializer\configu
ration.py", line 203, in load_from_file
    with open(config_file, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'config.yaml'

**Comment by dmfigol** [comment]
Both David and I suggested where to ask for troubleshooting help. This is not the right place.

**Comment by pravinrajgit** [comment]
Okay, got it. Thank you.
