### ISSUE TITLE
netmiko with intermediate SSH jumpserver using redispatch 

### ISSUE THREAD

**Issue by malaa2007** [nornir-automation/nornir#488]
Hello lions,

I need to use netmiko with redispatch option for Nornir, as it is working for me with netmiko using below template, but i need to apply it with Nornir and make it the default ssh for all use cases. Thanks

windows(script server) -- Linux(jump server) -- Router

jumpserver = {'device_type': 'terminal_server','ip': IP,'username': User,'password': Pass,'default_enter': '\r\n','global_delay_factor': 5}

net_connect = ConnectHandler(**jumpserver)

net_connect.find_prompt()
server = net_connect.read_channel()
net_connect.write_channel('ssh -l' + User + ' ' + Device)
net_connect.write_channel('\n')

redispatch(net_connect, device_type='cisco_ios', session_prep=False)

net_connect.send_command('\n')
net_connect.send_command('terminal length 0')
get_cdp_neighbor_details = net_connect.send_command("show cdp neighbor detail", delay_factor=5)
net_connect.send_command_expect('exit', expect_string=str(ServerPrompt))

redispatch(net_connect, device_type='terminal_server')

ServerPrompt = net_connect.find_prompt(delay_factor=1)
net_connect.disconnect()

**Comment by ogenstad** [comment]
Hi @malaa2007,

This issue tracker is for bugs and features for Nornir. For feature requests I will have to ask you to visit https://nornir.discourse.group/ or the #nornir channel within the Networktocode Slack team https://networktocode.herokuapp.com/

Closing this issue here.
