### ISSUE TITLE
NetBox add support for tags

### ISSUE THREAD

**Issue by egreenspan2** [nornir-automation/nornir#496]
Would like to propose pulling in tags from NetBox into nornir inventory, should be a simple add to the NB inventory plugin

nornir/plugins/inventory/netbox.py

`host["data"]["tags"] = d["tags"]`

This can make it much easier to deal with certain devices based on the tags from Netbox.

**Comment by wvandeun** [comment]
This PR can be closed. Implemented in NetBoxInventory2 for Nornir3.0.

**Comment by dbarrosop** [comment]
thanks for the heads up
