### ISSUE TITLE
3rd party plugin integration

### ISSUE THREAD

**Issue by patrickdaj** [nornir-automation/nornir#503]
Is there some documentation somewhere on how to integrate new plugins into nornir?  I can see the main plugins are in the core module and I'm trying to determine the best method of writing a few additional for check point mgmt api, pandevice and Ixia breaking point.  All three have pip installed modules I plan to utilize but are utimately APIs.  Is the best method to just drop my connection and task code into the pip installed nornir plugins directory or is there some other means of utilizing a 3rd party plugin that I am missing?

**Comment by dbarrosop** [comment]
As you probably noticed a task plugin is merely a function with a `task` argument so you can have them wherever you want as long as your code can reference it. There is no need to include the plugins with nornir and, as a matter of fact, we are working on separating the core nornir from the plugins, see #486 

If you want to see an example you can look at https://github.com/nornir-automation/nornir_napalm/tree/proposal which is work in progress but should work for you.

I am closing the issue as there is no actionable item here at this stage (I promise though I will improve docs for this as part of #486), feel free to keep asking questions here though if you have them or to engage in #486, help and feedback is appreciated
