### ISSUE TITLE
Maintainers for plugins

### ISSUE THREAD

**Issue by dbarrosop** [nornir-automation/nornir#504]
This issue is meant to track who is going to become the maintainer of nornir's plugins if/once #486 happens.

A few notes:

1. I am proposing myself some people already (marked as "maybe"), this is based on the history of git or online conversations
2. If you have been proposed and are not interested I apologize, let me know by any means and I will update the issue
3. If you are interested in volunteering, regardless of if there is a confirmed maintainer or not, let me know. There is no such thing as too many volunteers/maintainers :)
4. What this means is better discussed in #486. In any case, when we have a more complete list of maintainers and a better idea in #486 I will start conversations with all volunteers to make sure we are all good to go and to synchronize efforts.

Inventory:
 - ansible (@carlmontanari)
 - netbox (@wvandeun and @clay584)
 - nsot (orphan)
 - simple (to be included in the core)

Conections:
 - napalm (@dbarroso)
 - netconf (@ogenstad)
 - netmiko (@ktbyers)
 - paramiko (@dbarroso)

Functions:
 - print_result (needs some thought on how to best deal with this but will most likely stay in the core)

Processors:
 - print_result

Tasks (per category or connection plugin):
- jinja2: 
  - template_file (@dbarroso and @AchilleAsh)
  - template_string (@dbarroso and @AchilleAsh)
- None:
  - http_method (maybe @dmfigol)
  - command (@dbarroso)
  - gitlab (@wvandeun)
  - tcp_ping (@ogenstad)
  - write_file (@dbarroso)
- paramiko:
  - remote_command (@dbarroso)
  - sftp (@dbarroso)
- napalm: (dbarroso)
  - all of them 
- netconf: (@ogenstad)
  - all of them
- netmiko: (@ktbyers)
  - all of them

**Comment by ktbyers** [comment]
Yep, I can definitely do the Netmiko ones.

**Comment by carlmontanari** [comment]
Yeppers, I can do the Ansible inventory one!

**Comment by AchilleAsh** [comment]
Hi,

I'm not using nsot so I think I am not the most qualified to be involved in its plugin...
However I will gladly help with something else!

**Comment by wvandeun** [comment]
Open to work on netbox (and colab with @clay584 if he wants) and if no one else wants to do gitlab then I can take that one too.

**Comment by ogenstad** [comment]
Sounds good to me

**Comment by dbarrosop** [comment]
Quick update:
1. removed @AchilleAsh and flagged nsot as orphan
2. confirmed @carlmontanari for the ansible inventory
3. Confirmed @wvandeun for gitlab
4. confirmed @wvandeun for netbox (happy to update if @@clay584 wants to collaborate too)
5. confirmed @ogenstad for netconf
6. confirmed @ogenstad for tcp_ping

Just a quick note, I volunteered myself on a bunch of them but if someone would like to be responsible for them let me know. I'd rather focus on the core.

**Comment by AchilleAsh** [comment]
@dbarrosop I would be happy to help with the Jinja2 tasks!

**Comment by clay584** [comment]
Yes, I will help maintain the netbox plugin.

**Comment by dbarrosop** [comment]
Thanks, updated gitlab and jinja2 plugins adding @clay584 and @AchilleAsh respectively

**Comment by dbarrosop** [comment]
@AchilleAshI not sure if you are in the networktocode slack, if you are ping me, I have created a slack group in case there are quick questions/help needed in the process. Main discussion will still happen here though.
