### ISSUE TITLE
adapt paramiko plugin to nornir 3.0.0

### ISSUE THREAD

**Issue by dbarrosop** [nornir-automation/nornir#514]
Relates to #486 and #504 

Adapt plugin to nornir 3.0.0.

For reference look at https://github.com/nornir-automation/nornir_napalm.

Don't forget to add details to the plugin repository. You can do so by adding it [here](https://github.com/nornir-automation/nornir.tech.src/blob/master/data/nornir/plugins.yaml)

If you have any questions don't hesitate to ask.

**Comment by devon-mar** [comment]
I've moved the connection and tasks into a plugin [here](https://github.com/devon-mar/nornir_paramiko).

**Comment by dbarrosop** [comment]
Awesome! Would you like to update https://github.com/nornir-automation/nornir.tech.src/blob/master/data/nornir/plugins.yaml to reflect it?

Thanks!

**Comment by devon-mar** [comment]
Done! https://github.com/nornir-automation/nornir.tech.src/pull/26
