### ISSUE TITLE
adapt http_method plugin to nornir 3.0.0

### ISSUE THREAD

**Issue by dbarrosop** [nornir-automation/nornir#517]
Relates to #486 and #504 

Adapt plugin to nornir 3.0.0.

For reference look at https://github.com/nornir-automation/nornir_napalm.

Don't forget to add details to the plugin repository. You can do so by adding it [here](https://github.com/nornir-automation/nornir.tech.src/blob/master/data/nornir/plugins.yaml)

If you have any questions don't hesitate to ask.

**Comment by dbarrosop** [comment]
@dmfigol not sure if you want to take over this one, added the `help_wanted` label just in case but feel free to remove if you are good taking care of this

**Comment by ubaumann** [comment]
I created the basic plugin
https://github.com/InfrastructureAsCode-ch/nornir_http

**Comment by dbarrosop** [comment]
Awesome, thanks!
