### ISSUE TITLE
rethink env vars in configuration

### ISSUE THREAD

**Issue by dbarrosop** [nornir-automation/nornir#532]
I think it doesn't make sense to support directly. I think it might be easier to either:

1. Resolve the env vars directly in the config file
2. Just ignore env vars

After all, users can do:

``` python
otherwise_use_this = 123
nr = InitNornir(
    "config.yaml",
    core={"num_wokers", os.environ.get("MY_ENV_VAR", otherwise_use_this)
}
```

**Comment by dmfigol** [comment]
I've found the current implementation quite useful - I use `NORNIR_CORE_NUM_WORKERS` occasionally and it's nice that I don't need to do anything else to make it work.
Is the reason for this issue is because we dropped pydantic and this feature would be needed to be reimplemented?

**Comment by dbarrosop** [comment]
it’s cumbersome to implement, yes, and not worth the complexity IMO as you can do the same with the snippet above

**Comment by dbarrosop** [comment]
to expand on my previous answer, the feature is implemented, what’s annoying to implement is the previous order of operation where args > env vars > config. Right now I introduced a breaking change as the order is args > config > env vars. Not sure I want to fix that as the complexity explodes.

In any case, I am not sold on the idea of getting rid of this feature. Just added a note to consider/discuss before releasing

**Comment by ktbyers** [comment]
My vote would be to keep the environment variables (mostly from backwards compatibility and documentation perspective).

I would be fine with changing the order to `args > config > env vars`.
