### ISSUE TITLE
Nornir 3.0 - runners break task plugins on task.nornir.config

### ISSUE THREAD

**Issue by ktbyers** [nornir-automation/nornir#540]
This is the current pattern being used on the new nornir_napalm task plugins:

device = task.host.get_connection(CONNECTION_NAME, task.nornir.config)

But `task.nornir` was removed as part of the runner changes

https://github.com/nornir-automation/nornir_napalm/blob/master/nornir_napalm/plugins/tasks/napalm_configure.py#L29

**Comment by dbarrosop** [comment]
huh, thanks for reporting. I will check this one asap

**Comment by dbarrosop** [comment]
@ktbyers can you test #541? if it works I will release 3.0.0a3

**Comment by ktbyers** [comment]
Okay, that works. I tested with both ParallelRunner and SerialRunner using a use case that was failing earlier.
