### ISSUE TITLE
Discussion: Question about runner names

### ISSUE THREAD

**Issue by ogenstad** [nornir-automation/nornir#542]
The new runners were called ParallelRunner and SerialRunner, a thought I have was that the ParallelRunner should perhaps be renamed to ThreadedRunner. Both to better indicate how it is working, but also if other typs of parallel runners are introduced in the future.

What are your thoughts?

**Comment by dbarrosop** [comment]
Sounds good to me, do you want to open a PR renaming it?

**Comment by ogenstad** [comment]
Sure

**Comment by ogenstad** [comment]
Closing this was fixed in #544, don't know why it wasn't auto closed..
