### ISSUE TITLE
Cannot find plugins

### ISSUE THREAD

**Issue by brownjam** [nornir-automation/nornir#549]
First time using nornir, installed using pipenv and Python 3.6. The core module doesn't seem to find the necessary plugins.

I've installed like this:

`pipenv install nornir`
`pipenv install nornir_ansible`

`#!/usr/bin/env python`
`nornir import InitNornir`
`nr = InitNornir(`
`    core={"num_workers": 100},`
`    inventory={`
`        "plugin": "nornir.plugins.inventory.ansible.AnsibleInventory",`
`        "options": {`
`            "hostsfile": "./ansible_hosts",`
`        }`
`    }`
`)`

The error is:

`  File "/home/username/.local/share/virtualenvs/ansible-b1o-4AdT/lib/python3.6/site-packages/nornir/core/plugins/register.py", line 75, in get_plugin raise PluginNotRegistered(f"plugin {name!r} is not registered")
`nornir.core.exceptions.PluginNotRegistered: plugin 'nornir.plugins.inventory.ansible.AnsibleInventory' is not registered

For some reason there doesn't seem to be anything installed under the inventory folder:

`$ ls ~/.local/share/virtualenvs/ansible-b1o-4AdT/lib/python3.6/site-packages/**nornir**/plugins/inventory`
`total 12K`
`drwxr-xr-x 3 brownja fGVANetworkSupport 4.0K May 18 12:50 ./`
`drwxr-xr-x 8 brownja fGVANetworkSupport 4.0K May 18 12:41 ../`
`-rw-r--r-- 1 brownja fGVANetworkSupport    0 May 18 12:50 __init__.py`
`drwxr-xr-x 2 brownja fGVANetworkSupport 4.0K May 13 17:19 __pycache__/`

This looks better:

`$ ls ~/.local/share/virtualenvs/ansible-b1o-4AdT/lib/python3.6/site-packages/**nornir_ansible**/plugins/inventory`
`total 32K`
`drwxr-xr-x 3 brownja fGVANetworkSupport 4.0K May 18 12:28 ./`
`drwxr-xr-x 4 brownja fGVANetworkSupport 4.0K May 13 17:19 ../`
`-rw-r--r-- 1 brownja fGVANetworkSupport  15K May 13 17:19 ansible.py`
`-rw-r--r-- 1 brownja fGVANetworkSupport  134 May 13 17:19 __init__.py`
`drwxr-xr-x 2 brownja fGVANetworkSupport 4.0K May 13 17:19 __pycache__/`

Any information on how to search for plugins to register would be appreciated.

**Comment by dbarrosop** [comment]
what is the output of `pip freeze`? You seem to be mixing somehow `nornir 2.x` (current stable) and `nornir 3.x` (current beta that shouldn't be installed by pip unless explicitly indicated).

**Comment by dbarrosop** [comment]
Ok, I understand what happened to you. Do the following:

1. Destroy the virtual environment
2. Create a new one
3. Install `nornir` (do NOT install `nornir_ansible`)

Then your code should work.

Closing the issue but feel free to keep commenting if you run into problems.

**Comment by brownjam** [comment]
Thank you David, this solved it.
