### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'num_workers'

### ISSUE THREAD

**Issue by robbo7987** [nornir-automation/nornir#551]
Hi, i've just started getting to grips with Nornir. I have created the config.yaml, hosts.yaml and groups.yaml files in notepad++ and have only have these 3 lines of code to start with in python:

```
from nornir import InitNornir
nr = InitNornir(config_file="C:/Users/<REMOVED>/Desktop/config.yaml")
nr.filter(site="uk").inventory.hosts.keys()
```
I'm getting these errors:

```
Traceback (most recent call last):
  File "C:/Users/<REMOVED>/PycharmProjects/test_project/nornir_test.py", line 7, in <module>
    nr = InitNornir(
  File "C:\Users\<REMOVED>\PycharmProjects\test_project\venv\lib\site-packages\nornir\init_nornir.py", line 66, in InitNornir
    config = Config.from_dict(**kwargs)
  File "C:\Users\<REMOVED>\PycharmProjects\test_project\venv\lib\site-packages\nornir\core\configuration.py", line 279, in from_dict
    core=CoreConfig(**core or {}),
TypeError: __init__() got an unexpected keyword argument 'num_workers'
```
My config.yaml file looks like this:

```
---
core:
  num_workers: 10

inventory:
  plugin: nornir.plugins.inventory.simple.SimpleInventory
  options:
    host_file: "C:/Users/<REMOVED>/Desktop/hosts.yaml"
    groups_file: "C:/Users/<REMOVED>/Desktop/groups.yaml"
```

I have even tried starting it without the config file:

```
from nornir import InitNornir
nr = InitNornir(
    core={"num_workers": 100},
    inventory={
        "plugin": "nornir.plugins.inventory.simple.SimpleInventory",
        "options": {
            "host_file": "inventory/hosts.yaml",
            "group_file": "inventory/groups.yaml"
        }
    }
)
```
But STILL nothing, this isn't something stupid "Windows thing" is it because quite frankly i'm baffled at the moment.

Any help with this would be much appreciated, go easy i'm just a newbie with Nornir

**Comment by ktbyers** [comment]
Which version of Nornir do you have installed in your environment?

**Comment by robbo7987** [comment]
Version 2.4.0, i installed the package on PyCharm although I've tested the same file on the Windows cli as well were I've also installed Nornir and get the same error again. Initially i thought it must be the YAML file the way i've set it up but i'm getting the error when bypassing the config file as well, which points to it not being a YAML issue

**Comment by robbo7987** [comment]
I know it's probably coming across like i'm doing something wrong but i can honestly assure you all I've done is copy and paste the code above that bypasses the config.yaml file and ran it...same error. And created the 3 yaml files (config, hosts, groups) and tried it the other way to...same error.
I swear I think i'm cursed sometimes.

**Comment by dbarrosop** [comment]
I am closing this issue as this medium isn’t meant for support. There are other better channels for that.

In any case, I would recommend you to run `pip freeze` and double check you are indeed running nornir 2.4.0. That error doesn’t look right, looks like it’s coming from nornir 3 instead which is in alpha. If you have further comments feel free to drop
them here but I’d advise you to head to the forum or to slack.

Thanks

**Comment by dbarrosop** [comment]
I did look at the code and your error to be 100% sure and look at this error:

  File "C:\Users\<REMOVED>\PycharmProjects\test_project\venv\lib\site-packages\nornir\core\configuration.py", line 279, in from_dict

However, that file in `2.4.0` only has 140 lines:

https://github.com/nornir-automation/nornir/blob/v2.4.0/nornir/core/configuration.py

Also, that `from_dict` method was introduced recently in nornir3 (which is in alpha and you shouldn't be using yet :) )

**Comment by robbo7987** [comment]
Thanks, it was the version. On PyCharm i checked the version and it 100% said 2.4.0 but looking at it further it was the latest build i downloaded. The way PyCharms interface looks it genuinely did look like i'd downloaded 2.4.0 because when i clicked on Nornir it has it right next to it while looking for version details.
Thanks again though, you guys are awesome.
