### ISSUE TITLE
Nornir won't work with Telegraf Exec input plugin

### ISSUE THREAD

**Issue by ctopher78** [nornir-automation/nornir#571]
I've been attempting to use my automation tooling (built with Nornir) to pull metrics from devices using NAPALM and push those metrics to a TSDB using Telegraf.  I'm using the [Telegraf Exec plugin](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/exec) to log into routers and execute my scripts tooling. 

The Telegraf exec plugin expects the scripts being executes to send json to stdout.  So, the last line of my metrics script is this:

```
print(json.dumps(metrics, indent=2), end="")
```

I expected **only** the json string to be printed to standard out; however, there are also ascii color reset chars being sent to stdout:

**Expected**
```
[
  {
    "rx_errors": 3,
    "hostname": "cr01",
    "role": "Core",
    "site": "Blah",
    "interface": "cr01_Ethernet5/2/1"
  }
]
```

**Actual**
```
[
  {
    "rx_errors": 3,
    "hostname": "cr01",
    "role": "Core",
    "site": "Blah",
    "interface": "cr01_Ethernet5/2/1"
  }
] [0m[0m
```

The `[0m[0m` are causing the output to be non-valid json, which in turns cause telegraf to fail with this error:

```
2020-07-15T15:25:55Z E! [inputs.exec] Error in plugin: invalid character '\x1b' after top-level value
```

**Problem:**
I isolated my problem to how `colorama` is being initialized in the Nornir code here:
https://github.com/nornir-automation/nornir/blob/develop/nornir/plugins/functions/text/__init__.py#L16

```
init(autoreset=True, strip=False)
```

Specifically, the the `strip=False` parameter being set.  

The problem can be reproduced with this code:
```Python
import json 

from colorama import init

init(autoreset=True, strip=False)

print("")
```

```
python test.py > test.out
```

Contents of `test.out`
```
[0m
[0m
```

If you set `strip=True` or remove it altogether (default is True), the output no longer has the `[0m` chars.  I've also confirmed that this fixes my issue with Telegraf Exec plugin failing.

Given the `strip=False` setting was non-default, I'm assuming it was set for a reason.  I'm happy to create a PR, but I'm not sure of the background of enabling that perimeter, so I'm not sure the best way to resolve the issue.

**Comment by dbarrosop** [comment]
Mmm, I am afraid it was set due to cargo-culting. I say you propose the change and see if the tests are happy about it. Also, due to nornir3 split between core and plugins you will need to propose the same PR here:

https://github.com/nornir-automation/nornir_utils

Feel free to do so though once we are good with the one here.

See https://nornir.tech/2020/06/18/nornir-3-beta/ for more info.

Thanks and good job determining the underlying issue!

**Comment by ctopher78** [comment]
Thanks @dbarrosop - I found some other code in my library that uses the `termcolor` package.  When I set `strip=True` in the colorama init function, it somehow breaks `termcolor` term coloring...  Interestingly, it didn't seem to impact Nornir's/colorama's terminal coloring, from what I could find.  I'll dig in more and see if I can find a solution that doesn't break other terminal color packages being used with Nornir code.  I'd imagine someone using Nornir out there would be confused if their personal terminal coloring suddenly stopped working.

**Comment by ctopher78** [comment]
In case anyone else hits an issue using Nornir with with the [Telegraph Exec plugin](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/exec) and the [Telegraf JSON input format](https://github.com/influxdata/telegraf/tree/master/plugins/parsers/json).

You can workaround the problem by importing `colorama` and running the `deinit` function:

Code intended to push metrics using Telegraf
```
from colorama import deinit

   # code collecting metrics
   # .. 
    
    colorama.deinit()
    print(json.dumps(metrics), end="")
```
