### ISSUE TITLE
requesting comment for ansible-like patterns 

### ISSUE THREAD

**Issue by sjtarik** [nornir-automation/nornir#575]
Hi @dbarrosop, @ktbyers 

Following up on Slack conversation for developing ansible-like patterns in nornir. Do you think this would be anti-pattern?

`nr.filter(Ansible_F('sjc1:&junos:&!decomm'))`

Let say this is for devices in groups "sjc1", "junos" and not "decomm". It is easily achievable with F and all/any functions in code but in an automation that takes slack messages or console arguments it needs some translation/massaging to generate those filters dynamically from given user input. 

`ansible-playbook dummy.yaml -e "hosts=sjc1:&junos:&*br*"`

Another distinction is use of regular expressions in given strings, one can provide a string like "sjc1*" and it would match both groups and hosts matching that pattern. It is again achievable by filter_func and iterating thru hostname and its groups with a re.match but if it is not anti-pattern could be something useful for folks like me transitioning from Ansible.

So overall I wonder if these two approach would be OK within nornir framework. I am coming from an Ansible workshop transitioning into Nornir and want your feedback on contributing this filter part within the framework or keeping it outside the nornir.

Tarik

**Comment by sjtarik** [comment]
I guess it all boils down to if such a function would fit in filters:

  ```
class FSTAR(F):
      def __handle(self, host):
        pat = next(iter(self.filters.values())
        for g in host.groups:
          if re.match(pat, g):
            return True
        return bool(re.match(pat, host.name) is not None)

      def __call__(self, host: Host) -> bool:
        return self.__handle(host)

      def __invert__(self) -> "F":
        return NOT_FSTAR(**self.filters)
```

**Comment by dbarrosop** [comment]
Mmm, I think it's an awful pattern :P and not very expressive ;) In any case, as you suggest it's a matter of parsing the string and returning the equivalent F object. I'd suggest moving the discussion here:

https://github.com/carlmontanari/nornir_ansible

As it'd probably make sense to ship this with the ansible inventory once we release nornir3.

**Comment by dbarrosop** [comment]
I am closing this as this is no longer relevant for nornir-core.

Thanks!
