### ISSUE TITLE
[Question] How to automate Nornir

### ISSUE THREAD

**Issue by FloLaco** [nornir-automation/nornir#577]
Hi guys,

I have multiples projects for automate our large network. 
We had adopt Kubernetes plateform in GCP to host our network automation solution. 
My goal is to offer to our clients, NOC, etc an API/web interface for doing some actions in our network : 
- gather facts
- configuration use cases (ex: adding a vlan, a VRF, adding a static route to our VXLAN fabric, deploy a new site, etc ...)

Nornir is great for "playing" with lot a device and I am considering to use it in my network automation architecture, but since it will be hosted in Kube, I don't want user to have a ssh access to launch Nornir.
We are developing custom API for some actions (IPAM, Firewall, etc).

Is there a way, from our custom API in Python to launch Nornir and get the result (in JSON) ?
As Nornir will be long to execute the task, I have to think about non-blocking API.

I love Ansible for their AWX which offer REST API to manipulate Ansible (launch it, choose the network perimeter, etc ...). 

I hope I'm in the good place for asking this kind of question

**Comment by dbarrosop** [comment]
I am closing this issue as this is not an actual issue and there isn't anything to do here, however, if people wants to discuss this here you are all welcome.

My two cents:

1. I'd start by implementing an API with flask exposing the RPCs you need
2. To deal with long tasks asynchronously:
   1. The RPC would return immediately with some sort of task id
   2. The RPC would store in some document db (i.e. mongodb/crockroachdb) the state of the execution at every step and, in the end, the
   3. Some service (or the same) would allow users to query the state of the tasks based on the task id returned previously

**Comment by FloLaco** [comment]
Thank you for your reply @dbarrosop. 
This is what we will do, but in a REST"way".

What I (badly) asked is, does Nornir or some other library offer the ability to "control" Nornir (i.e. run Nornir, catch the output, catch errors for each device, etc.) from a external application ?

Design : 
                                 API Call (or similar)                                                           Run tasks
REST API (in Python) ---------------> "Nornir manager"  -----------> Nornir ---------------->device(s)


Where can we talk about it ? It's related to Nornir (how to launch it/manipulate it)

**Comment by ogenstad** [comment]
Either https://nornir.discourse.group/ or #nornir in the Slack community would be good places to start.

**Comment by dbarrosop** [comment]
no, there are very good tools already to quickly build a control system to trigger nornir so it hasn't been a priority (i.e., flask if you want full control or stackstorm if you want something ready-made)
