### ISSUE TITLE
Plugin netbox, filter by "custom_fields" on "device-types"

### ISSUE THREAD

**Issue by berishap** [nornir-automation/nornir#585]
Hi,

is it possible to device types (netbox URL: /api/dcim/device-types/) as a filter?
More specific, is it possible to filter based on "custom_fields" to access only a subset of the hosts?

I have read the source code, and there is no request going to "/api/dcim/device-types/", so I assume this is not possible, correct?

Thank you.

**Comment by dbarrosop** [comment]
Closing this issue as this is not the right place for this kind of question and there isn't anything to do here.
