### ISSUE TITLE
Incompatibility 2.5.0 to 3.0.0 - get_defaults_dict

### ISSUE THREAD

**Issue by kpeterson-sf** [nornir-automation/nornir#591]
I received the email fro K Byers that included a link to incompatibility.  Thanks that is great.

I think there is one that might need to be noted and/or fixed.  Looks like the inventory get_defaults_dict() was removed from the Inventory class and it impacts my inventory "transform" function. 

 It's quick enough to fix by accessing the defaults directly.  

Can we consider adding it back or is there some underlying reason not to?

**Comment by kpeterson-sf** [comment]
I see it's noted in another place.

**Comment by dbarrosop** [comment]
For reference, it provided no extra functionality as it was a redundant method as there is already a `dict` method that provided the same functionality.
