### ISSUE TITLE
Documentation clarifications

### ISSUE THREAD

**Issue by candlerb** [nornir-automation/nornir#592]
Greetings!

Nornir looks extremely interesting, speaking as a frustrated ansible user frequently tripped up by [Greenspun's Tenth Rule](https://en.wikipedia.org/wiki/Greenspun%27s_tenth_rule).

However, having read the documentation, there are some key things that are unclear to me, and maybe to other newcomers too.  I expect they are obvious to someone who is immersed in Nornir, but it would be great to be clear about these up-front.

1. The most fundamental question is: does a [task](https://nornir.readthedocs.io/en/3.0.0/tutorial/tasks.html)'s python code run on the local host (where nornir is running), or the remote host (as specified in the inventory)?

    My first guess was that the python code is copied to the remote host and run there, like ansible.  Otherwise, the "hello_world" example seems pretty pointless, if all it does is generates some text on the local host and doesn't connect to the remote host at all!   This would imply that the remote host needs a python interpreter.

    However, the inventory examples have many network devices (e.g. eos, junos).   Surely these don't all have python interpreters??  What about network devices accessed via [napalm](https://nornir.readthedocs.io/en/3.0.0/howto/handling_connections.html?highlight=napalm)?

2. What's the function of the "connection_options.platform" field in the inventory?  Does it affect how the Task is run, and if so, how?  Are there specific allowed values of "platform", and if so, what are they?

3. If a Task is run remotely, what userid does it run as?  If we want it to run as "root", is it up to the user to ensure that the ssh connection logs in as "root", or else explicitly runs "sudo" when required?

I think it would be very helpful if there were more realistic Task examples than just saying hello.  I suggest the following two.

1. Say I want to install a package on a remote Linux host.  Basically all I need to do is to run `apt-get install -y apache2` on that host.

    What does that task look like?  Should it be

    ```
    def install_apache2(task: Task) -> Result:
        return Result(
            host=task.host,
            result=subprocess.run(["apt-get","install","-y","apache2"], check=True)  # with or without sudo?
        )
    ```

    Or does this task run locally, which implies I have to use something like `task.host.get_connection(...)` to obtain an ssh connection and push a command down it?

2. Now say have a Cisco IOS device, and I want to run "show run" on that device and collect the results.  Again, how should I do it?

    There is a tiny example [here](https://nornir.readthedocs.io/en/3.0.0/howto/handling_connections.html#Automatically) which shows calling napalm_get.  I think this implies the Task runs on the *local* host rather than the remote one, and it is internally invoking napalm to do the request.

    The [nornir-napalm](https://github.com/nornir-automation/nornir_napalm) repository doesn't have any further examples that I can see.

Thanks in advance for your time.

**Comment by candlerb** [comment]
After some testing / reverse engineering: all tasks run locally.  The "hello_world" example doesn't connect to anything.  It works fine with the sample dummy inventory.

Still working on trying to get `task.host.get_connection(X, Y)` working though.

**Comment by dbarrosop** [comment]
1. correct
2. this is to provide consistency amongst connection plugins that may use ssh as transport (i.e. netmiko, some napalm drivers and paramiko, although the last one is abandoned)
3. There used to be a paramiko plugin but nobody took care of it once I split the core and the plugins. You can find it in any of the the 2.x branches if you are interested.
4. Correct
5. netmiko and napalm both use platform to select the relevant underlying driver
6. I am afraid I am not sure what you mean in the last paragraph.

I am closing the issue as I don’t think there is an actionable work to do but feel free to keep commenting.

**Comment by candlerb** [comment]
Thank you.

In the last paragraph, I was observing that the nornir_napalm and nornir_netmiko plugins don't use the "platform" attribute to select the **connection plugin**, because they hard-code the name of the connection plugin that they use.

However, now I see that `nornir_napalm` uses the platform to select the **napalm network driver name**:
* https://github.com/nornir-automation/nornir_napalm/blob/master/nornir_napalm/plugins/connections/__init__.py#L55

With `nornir_netmiko` it's a bit more complicated: roughly the platform is used as the **netmiko device_type**.  However the platform is first looked up in `napalm_to_netmiko_map`, and passed through unchanged if not found in that table:
* https://github.com/ktbyers/nornir_netmiko/blob/master/nornir_netmiko/connections/netmiko.py#L10
* https://github.com/ktbyers/nornir_netmiko/blob/master/nornir_netmiko/connections/netmiko.py#L54

Which in short means: "use the napalm network driver name as the platform if you can, otherwise use the netmiko `device_type` name"

"linux" is one of the "regularly tested" [netmiko device_types](https://pynet.twb-tech.com/blog/automation/netmiko.html) - therefore it appears that the inventory examples with `platform: linux` are intended to be used with netmiko.

At least, I think that's right :-)

**Comment by dbarrosop** [comment]
yeah, that’s correct. Basically tasks decide what connection plugin to use (most are named napalm_something/netmiko_something/netfconf_something so there should be little doubt here :P), that’s the get_connection type and then the connection plugin will use the platform to know more details about the device if they need to. Reasons to know this info will vary depending on the underlying library. Nornir’s goal is not to hide any underlying library from the user so users are still expected to understand what they are doing. Nornir only tries to provide facilities to help build reusable building blocks (inventory plugins, runners, processors, etc)
