### ISSUE TITLE
Bad hyperlink in documentation

### ISSUE THREAD

**Issue by candlerb** [nornir-automation/nornir#593]
At https://nornir.readthedocs.io/en/3.0.0/tutorial/processors.html there is a hyperlink:

> check the [class documentation](https://nornir.readthedocs.io/en/ref/api/processors.rst)

but this gives a 404.

**Comment by dbarrosop** [comment]
Will try to fix at some point but I’d be more than happy if someone beats me to it. For reference, correct link is:

https://nornir.readthedocs.io/en/3.0.0/api/nornir/core/processor.html#nornir.core.processor.Processor

Thanks!

**Comment by ubaumann** [comment]
I saw it and found a couple of other old liks to ../../ref/api
I hope I can fix it in the next days and test it

**Comment by mjbear** [comment]
I found the old `ref/api` link in the latest docs so I put together a PR for this.

**Comment by mjbear** [comment]
@dbarrosop 
This issue ticket 593 can be resolved since PR 903 fixes it. Thank you!
