### ISSUE TITLE
[ Feature ] Host filtering with regex support 

### ISSUE THREAD

**Issue by network-shark** [nornir-automation/nornir#597]
Hey , 

it would be really handy if we could filter the inventory hosts based on regex. 

If you have a good naming schema for your routers , then it is really powerful for targeting.  

I tried to understand the filter code , but I suck at oop. :/

Thank You !

**Comment by dbarrosop** [comment]
You can do that already with the `filter_func` option, is there any particular reason or case that you think that might not be an option? Asking because I think the `F` object is complex enough already to keep adding features there as people often struggles understanding how it works.

**Comment by network-shark** [comment]
I have missed this option , sorry about that. We can close this issue. Thanks for pointing me to the right direction :-)

**Comment by dmfigol** [comment]
This can be addressed by existing functionality as David mentioned, so closing this.
