### ISSUE TITLE
[Feature request] Inventory filtering operator:  <int> in <iterable>

### ISSUE THREAD

**Issue by RuiMeireles** [nornir-automation/nornir#606]
This is sample data from my hosts file:
```
data:
  site: London
  site_id: 10
```

I would like to be able to filter hosts by checking if these data keys values (integers, strings, ...) are present in a list.
Something like this:
```
F(site__in=["London", "Stockholm"])
F(site_id__in=[10, 11, 12])
```

Currently, the `__in` operator isn't implemented. I believe it would be a nice feature to have.
The closest is the `__any` operator, but it only works with iterables. (Curiously, if the left operand is a string then `__any` will work just as intended)

This was discussed with @dbarrosop and @dmfigol on 2020-10-18 in the #nornir networktocode slack channel.

**Comment by dbarrosop** [comment]
#608 should fix your issue, feel free to test it and let me know
