### ISSUE TITLE
Severity_level is override when error

### ISSUE THREAD

**Issue by FloLaco** [nornir-automation/nornir#609]
Hi,

I've created a task that return this : 
```
        Result(
            host=task.host,
            failed=True,
            severity_level=logging.CRITICAL,
            result=f"syslog cannot be configured {task.host.name}."
        )
```
The problem is, when a task is `failed`, the `severity_level` is always set to `logging.ERROR` (https://github.com/nornir-automation/nornir/blob/8e90cec8b3df30ff6a0e1541e7156d69780b3ee9/nornir/core/task.py#L123).
I think, if severity_level can be used by ourselves, it should not be override.

I change this [line](https://github.com/nornir-automation/nornir/blob/8e90cec8b3df30ff6a0e1541e7156d69780b3ee9/nornir/core/task.py#L123) by : 
`r.severity_level = logging.ERROR if r.failed and (r.severity_level == self.severity_level) else r.severity_level`

If the task `failed`, we should set to `logging.ERROR` only if the actuel severity_level is the default one (`self.severity_level`).
What do you think about it ?

**Comment by dbarrosop** [comment]
yeah, I think that makes sense. Would you mind opening a PR?

**Comment by FloLaco** [comment]
@dbarrosop no problem to make a PR with tests accordingly.

**Comment by FloLaco** [comment]
PR merged. I close this issue.
Thanks to you David
