### ISSUE TITLE
Feature Request: Add ip_address attribute to Host Object

### ISSUE THREAD

**Issue by renatoalmeidaoliveira** [nornir-automation/nornir#610]
In some network scenarios the device hostname has a meaningful value to the organization and hasn't a DNS entry, for that reason it would be great if the ConnectionOptions object was instantiate with some think like
``` python
d = ConnectionOptions(
                hostname= self.ip_address if self.ip_address is not None else self.hostname
                port=self.port,
                username=self.username,
                password=self.password,
                platform=self.platform,
                extras={},
            )
```

**Comment by dbarrosop** [comment]
The `Host` object already distinguishes between the `name` (the key assigned to it in the yaml file when using the `SimpleInventory`) and the `hostname` so you already have this differentiation. Put the "meaningful value" in the key so it becomes the name and put the IP in the hostname to achieve what you are describing.

**Comment by renatoalmeidaoliveira** [comment]
Great, thank you.
