### ISSUE TITLE
Inheritance Issue

### ISSUE THREAD

**Issue by no-such-anthony** [nornir-automation/nornir#621]
There appears to be an inheritance issue as found by Netigo @ https://nornir.discourse.group/t/inheritance-problem/645

If you recreate the inventory files at https://github.com/nornir-automation/nornir/blob/develop/docs/tutorial/inventory.ipynb

Then try

```
leaf01_bma = nr.inventory.hosts["leaf01.bma"]
print(leaf01_bma["domain"])  
```
The data is supposed to come from the group `global`, but instead comes from defaults.yaml, ie acme.local.  It should be global.local as mentioned in the documentation.

I've attempted a possible patch but not sure how correct it is within the Nornir framework.

In `nornir/core/inventory.py`

Modify the group loop in `_resolve_data` 

    for g in self.groups:
        for k, v in g.data.items():
            if k not in processed:
                processed.append(k)
                result[k] = v

        for pg in g.groups:
            for k, v in pg.data.items():
                if k not in processed:
                    processed.append(k)
                    result[k] = v

Modify the group loop in `__getitem__`

        for g in self.groups:
            try:
                r = g.data[item]
                return r
            except KeyError:
                pass

            for pg in g.groups:
                try:
                    r = pg.data[item]
                    return r
                except KeyError:
                    pass

**Comment by dbarrosop** [comment]
thanks for reporting, I opened #623 which should address this bug

**Comment by no-such-anthony** [comment]
Thanks!  Re #623 - Looks great.  I think it may still need a change of g.items() to g.data.items() in _resolve_data?  And maybe a .values() test for this scenario?

**Comment by NetIgo** [comment]
Thank you.
Looks good.

**Comment by no-such-anthony** [comment]
Something that returns an ordered list of all the groups might help in _resolve_data and __getitem__?  Example

```
    def __ordered_groups(self, groups):
        og = []
        for g in groups:
            og.append(g)
            if len(g.groups) > 0:
                og.extend(self.__ordered_groups(g.groups))
        return og
```
`for g in self.__ordered_groups(self.groups):`

**Comment by no-such-anthony** [comment]
Another function that needs checking on, `__getattribute__` .  If the username was in group `global` like the original example, it would be missed.

Possible fix for `__getattribute__` , using something that returns a complete group list like above, 

```
           for g in self.__ordered_groups(self.groups):
                r = object.__getattribute__(g, name)
```

**Comment by dbarrosop** [comment]
Thanks, I will try to find time to look into your comments. Just a tip, these comments would be easier to track on the PR alongside the code.
