### ISSUE TITLE
How to use Delay factor and  expect string in Nornir?

### ISSUE THREAD

**Issue by mohitbhardwaj5659** [nornir-automation/nornir#627]
Hi Kirk ,

Happy New year to you.

Problem statement :
I have prepared one script to upgrade the nexus 9k devices but i am facing some issues running some command.
I am trying to run some commands on the nexus 9k switches running on version 9.3.4 using Nornir .Commands are given below .
1.show file bootflash:"+str(self.image)+" sha256sum"
2.install all nxos bootflash:///"+str(self.image_to_upgrade)+" non-disruptive"

But this command is taking a long time to execute and it is giving the below error.
OSError: Search pattern never detected in send_command
In order to eradicate that error i have used "use_timing" parameter.
upgrade_to_new_version = r2.run(
                                 task = netmiko_send_command,
                                 use_timing = True,
                                 command_string = install_upgrade
                                 )
-----------------------------------------------------------------------------------------------------------
show install all impact nxos bootflash:///"+self.image_to_upgrade
For checking the hardware compatibility i am using the netmiko module directly(not using nornir in this case)
connection= {
                           "device_type": "cisco_nxos",
                           "host": host_ip,
                           "username": "mohit",
                           "password": "Orange@123",
                           "fast_cli": True

                        }

But it is again not showing any OS error but i am not able to write the output to a file.
Please address the issue and suggest any changes that need to be done .

Thanks 
Mohit

**Comment by mohitbhardwaj5659** [comment]
Can please somebody help in this ?

**Comment by ktbyers** [comment]
https://github.com/nornir-automation/nornir/discussions/633
