### ISSUE TITLE
Cannot use Netmiko_file_transfer module to load source file from memory

### ISSUE THREAD

**Issue by sindhujit1** [nornir-automation/nornir#634]
I want to load the contents of a certificate .cert and .key filr from memory or that stored in a variable. But I am unable to do that using this module in nornir. It only seems to allow from a source file. That is not possible since our security team will not allow private keys to be stored on our VMs.

```
nr = InitNornir(config_file=project_path +"/standalone/config.yaml",logging={"enabled":False})
		nr_nxos = nr.filter(F(hostname__in=['x.x.x.x']))
		nornir_set_creds(nr_nxos,fabricList,['x.x.x.x'])
		source_file = project_path + "/arista/certs/" + key_file
		result = nr_nxos.run(
			task=netmiko_file_transfer,
			source_file=source_file,
			dest_file=key_file,
			direction='put',
			num_workers=1,
		)
```

Please advise if there is way to achive this using nornir.

**Comment by ktbyers** [comment]
The `netmiko_file_transfer` mechanism always stores the file on the file system so you would need to create an alternate mechanism to do this (if you can't use the file system at all).
