### ISSUE TITLE
Task repr bug

### ISSUE THREAD

**Issue by amitmi704** [nornir-automation/nornir#639]
# Summary
[`repr()`](https://docs.python.org/3/library/functions.html#repr) expects a string to be returned.  `nornir.core.task.Task.__repr__` returns the object stored in `self.name` without type-casting it.  This prevents the use of non-string objects for the `name` kwarg of a `nornir.core.task.Task`.

# Example - Break
```
from typing import Any

class Test:
    def __init__(self, test: Any) -> None:
        self.name = test
    def __repr__(self) -> str:
        return self.name

a = Test("this will work")
b = Test({"this": "will not work"})

print(a)

try:
    print(b)
except TypeError:
    print("TypeError")
```

# Example - Fix
```
from typing import Any

class Test:
    def __init__(self, test: Any) -> None:
        self.name = test
    def __repr__(self) -> str:
        return repr(self.name)

a = Test("this will work")
b = Test({"this": "will now work"})

print(a)
print(b)
```

# Test Results
Local run of `poetry run pytest` does not produce a failure.

**Comment by ktbyers** [comment]
Personally, I don't think this is worth fixing/changing. I think it is pretty self-apparent that self.name is a string. Also type-hints in Nornir indicate it should be a string.

So I would say don't do the above (i.e. always set self-name to be a string).

**Comment by dbarrosop** [comment]
I concur with Kirk, would you mind explaining why is this an issue? `name` is defined as a string so `__repr__` shouldn’t need type casting.

**Comment by amitmi704** [comment]
I missed the type hint on the `__init__`.

My use case is standardizing the task names using `Enum`s.  I can re-work my interfaces to use the `name` attribute of the `Enum`s and get the same effect.  This isn't necessary if you're not thinking it fits.
