### ISSUE TITLE
Documentation - filtering tutorial/how-to guide

### ISSUE THREAD

**Issue by writememe** [nornir-automation/nornir#643]
# Introduction
I'm opening this issue as per some discussions with @dbarrosop  regarding adding some extra documentation around filtering. I've done quite a bit of work in my own [repo](https://github.com/writememe/nornir-filtering-demo), but looking to be a good citizen and put it into the core documentation :)

## Items for consideration/direction

I'm happy to do this in whatever format you choose, but I'd like that to be approved before I spend heaps of time not doing something which doesn't suit the maintainers. Here are some things which I need some clarification on:

1) Can you confirm that you would like it in this [Jupyter notebook style format?](https://github.com/nornir-automation/nornir/blob/master/docs/howto/advanced_filtering.ipynb) If so, any tips/guides would be appreciated on best ways to do this. If not, I'll try work it out.
2) Would you like me to stick to the sample inventory used throughout the documentation? It may read better and be more coherent to the end user, but also be more work for me.
3) This [cheatsheet](https://github.com/writememe/nornir-filtering-demo/blob/main/CHEATSHEET.md) seems like it should have a home somewhere. Would you like this included in the docs, and if so where?

Any questions about above or things you'd like me to take into consideration, please let me know.

**Comment by dbarrosop** [comment]
Yeah, jupyter notebooks should be the way to go. Jupyter shouldn't be hard to pick given you have plenty of python experience; install it in the same venv as nornir and execute `jupyter notebook`, then go to the URL indicated on your shell and off you go, rest is just a combination of python and markdown. The important bit to remember is that once you are done with the netbook you should run `make nbval` to test it (your notebook will have to be located under `howto` or `tutorial`, if you think some other structure is preferred we can discuss it).

Re the inventory itself, feel free to do what you think it's best to convey your message, the important bit here is that people learns :)

Mmm, the cheatsheet is interesting, I'd suggest two things:

1. A new top-level section in the documentation (right after howto)
2. A link in a new discussion entry [https://github.com/nornir-automation/nornir/discussions/categories/q-a] so people can find it

By the way, if people wants to "sign" contributed tutorials/howtos I am good with that. If adding a link to linkedin/blog/twitter/gh/whatever helps encouraging people I am more than glad to let people do it (I understand lots of people blog for visibility), also, cross-referencing should be more than fine (i.e. adding a tutorial and then writing on your blog about the tutorial with links).

Thanks for chiming in :)

**Comment by writememe** [comment]
> A link in a new discussion entry [https://github.com/nornir-automation/nornir/discussions/categories/q-a] so people can find it

For sure, I've added a post and a reference to it here: https://github.com/nornir-automation/nornir/discussions/647

In relation to the other comments, I'll add the this to my list and aim to knock it out in the next month or so. I also won't sign the contribution/tutorial, I'm not that vain!

**Comment by writememe** [comment]
hi @dbarrosop, I've finally got around to starting this. I took me a while to work out poetry etc but now I'm up and running.

I hope to get a draft out for review in the next week or two, so you can give me some feedback. I also felt the need to explain custom data in a bit more detail, so that my how-to is easier to comprehend. It's probably going to be quite long, but hopefully that's a good thing :sweat_smile:

**Comment by writememe** [comment]
I am going to close this issue now as we've completed this. Thanks again for your help
