### ISSUE TITLE
Inheritance model bug

### ISSUE THREAD

**Issue by c-cj** [nornir-automation/nornir#646]
![image](https://user-images.githubusercontent.com/32269078/107039557-05fe4680-67f9-11eb-8ef4-05627147ada6.png)

not comes from the group `global`, comes from defaults

![image](https://user-images.githubusercontent.com/32269078/107039635-20382480-67f9-11eb-8667-6ec4e462e1bd.png)

![image](https://user-images.githubusercontent.com/32269078/107040050-a9e7f200-67f9-11eb-93d9-b4d3498105f3.png)

**Comment by dbarrosop** [comment]
Thanks for reporting this issue. This was fixed in #623 but it hasn't been released yet. I will try to release in the next few days the bug fix.

**Comment by kpeterson-sf** [comment]
Thanks for the fix @dbarrosop.  Any ideas when this might make it into a release?

**Comment by dbarrosop** [comment]
I just did, apologies for the delay
