### ISSUE TITLE
Nornir state property returning GlobalState class, not object

### ISSUE THREAD

**Issue by brandomando** [nornir-automation/nornir#666]
https://github.com/nornir-automation/nornir/blob/e4f6b8c6258ae2dcfb286098b30652c7a31ecf30/nornir/core/__init__.py#L177

I'm not sure if this is intended behavior but it is a bit confusing to me why there would be a need to return the `GlobalState` class rather than the instantiated object like the `data` attribute, which is an instance of `GlobalState`.

**Comment by dbarrosop** [comment]
`GlobalState` used to be a singleton but that's no longer true so I think this is a leftover. As a matter of fact, `state` is redundant as `data` is what we care about nowadays.

**Comment by brandomando** [comment]
I thought that might be the case. I will submit a PR to remove it.

**Comment by dbarrosop** [comment]
Thanks!
