### ISSUE TITLE
Unable to start nornir in MAC

### ISSUE THREAD

**Issue by rg0809** [nornir-automation/nornir#687]
While starting nornir getting below error

```
>>> from nornir import InitNornir
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'InitNornir' from 'nornir' (/Users/r/PycharmProjects/NWScripting/venv/lib/python3.9/site-packages/nornir/__init__.py)
```

nornir version 3.1.1

**Comment by ktbyers** [comment]
Probably try using PIP to uninstall and re-install nornir in your given virtual environment.

```
pip uninstall nornir
pip install nornir
```

If you get the same error, then you need to show the contents of this file:

```
/Users/r/PycharmProjects/NWScripting/venv/lib/python3.9/site-packages/nornir/__init__.py
```

It is very, very likely an environment issue on your side.

**Comment by rg0809** [comment]
Thanks kybyers, indeed it was a environment issue. I had another package installed which was conflicting; uninstalled the package and it's now working for me.
