### ISSUE TITLE
grouped tasked stop if any grouped tasks fail

### ISSUE THREAD

**Issue by qman28** [nornir-automation/nornir#699]
There seems to be no way to continue grouped tasks if any of them fail.  On the main task you can use 'on_failed=True' but that does not seem to work for grouped tasks.

```
def sub_task1(task: Task) -> Result:
	return Result(host=task.host, failed=True)

def sub_task2(task: Task) -> Result:
	return Result(host=task.host, result='Hello')
	
def main_task(task: Task) -> Result:
	task.run(task=sub_task1) #fails on purpose
	task.run(task=sub_task2, on_failed=True) # does not get called

nr.run(task=main_task)
```

[Here](https://github.com/nornir-automation/nornir/blob/53a721f412a597df04bad2b31a76074d2ea53731/nornir/core/task.py#L169) I believe is the problem.

```
        r = run_task.start(self.host)
        self.results.append(r[0] if len(r) == 1 else cast("Result", r))

        if r.failed:
            # Without this we will keep running the grouped task
            raise NornirSubTaskError(task=run_task, result=r)

        return r
```

It will always kill a failed subtask and not allow more subtasks to be run.

**Comment by dbarrosop** [comment]
Subtasks are treated like regular functions so if you don't want them to trigger a failure you should use `try...except...`.

``` python
def main_task(task: Task) -> Result:
    try:
        task.run(task=sub_task1) #fails on purpose
    except Exception as e:
        # I actually don't care if this happens and want to continue
        pass
    task.run(task=sub_task2)
```

As a matter of fact, a subtask failing shouldn't flag the host as failed. Only "main" tasks failures will, that is done by design so you can implement your own recovery logic/mechanisms easily.
