### ISSUE TITLE
on_failed=True doesn't seem to work on group tasks (sub tasks level)

### ISSUE THREAD

**Issue by jasonhaominglo** [nornir-automation/nornir#712]
Hi guys,

Just wanted to ask if there is a workaround for this - from what i can gather, the on_failed=True does not work at the subtask level. I have seen commentary that it works on the main task level but this doesn't seem to hit my use case where the failures are happening below this level.

**Comment by dbarrosop** [comment]
Can you post more details and/or an example?

**Comment by jasonhaominglo** [comment]
Hi David,

apologies - just noticed that this was already covered by a previous logged ticket #699
