### ISSUE TITLE
providing enable secret for Cisco devices outside hosts.yaml

### ISSUE THREAD

**Issue by bit-git** [nornir-automation/nornir#718]
How can I provide enable secret for Cisco devices without adding as optional args in the hosts.yaml?

Got help for password from - https://github.com/ktbyers/nornir_test/blob/master/nornir_test/nornir_utilities.py

How can I extend Kirk's code to add secret?

Thank you

**Comment by ktbyers** [comment]
See this discussion here:

https://github.com/nornir-automation/nornir_napalm/issues/17

Netmiko connection options would just use a "netmiko" key.

If you still are still having issues, then just update the above referenced issue.
