### ISSUE TITLE
Retrieve task result in between multiple tasks?

### ISSUE THREAD

**Issue by ozschmoz** [nornir-automation/nornir#752]
Is there any way task results could be retrieved before logging off switch in order to perform follow-up tasks based on output? I'm wondering if it's possible to perform everything within a single switch ssh access when further actions are based on result output.

**Comment by dbarrosop** [comment]
That is how nornir works by defaukt, connection is reused amongst different tasks on the same device.

**Comment by ozschmoz** [comment]
@dbarrosop right, but what do you do when the second task depends on the output of the first one?
