### ISSUE TITLE
Re-run GitHub Actions Workflow

### ISSUE THREAD

**Issue by ubaumann** [nornir-automation/nornir#773]
The last GitHub Actions failed with the error `Version 3.6 with arch x64 not found` even if it should work. 
https://github.com/nornir-automation/nornir/runs/5062733087?check_suite_focus=true#logs
I run the test in my fork and everyting works well so I guess a simple "Re-run all jobs" should do the trick.

![image](https://user-images.githubusercontent.com/2352402/152699500-cd51a73a-60a9-4fa5-8382-5482ce3e61c9.png)

**Comment by dbarrosop** [comment]
Re-running isn't going to achieve anything, problem seems to be that github is phasing out python 3.6, which is understandable as py3.6 is EOL.

**Comment by dbarrosop** [comment]
The error says it is not available:

https://github.com/nornir-automation/nornir/runs/5097222304?check_suite_focus=true#step:3:6

I look a bit more onto it and looks like we are using windows 2022, which doesn't have it:

https://github.com/actions/virtual-environments/blob/main/images/win/Windows2022-Readme.md#python

So I think what happened is that we use `windows-latest` as the platform and gh probably change this to 2022 recently.

I think we should deprecate py3.6 as it is EOL, probably add 3.10 instead. I am going to ping @ktbyers before we go down that path in case he has strong opinions against it. If we deprecate py3.6 we should change it [here](https://github.com/nornir-automation/nornir/blob/develop/pyproject.toml) too.

**Comment by dbarrosop** [comment]
Great! @ubaumann do you want to open a PR?

**Comment by ubaumann** [comment]
I am sorry I missed the last comment. I will make the PR :)

**Comment by ubaumann** [comment]
Created the PR https://github.com/nornir-automation/nornir/pull/780

**Comment by dbarrosop** [comment]
No worries, and great work with that PR.

Solved by #780
