### ISSUE TITLE
Will Nornir be updated to support newer versions of dependencies such as typing-extensions v4.x?

### ISSUE THREAD

**Issue by fseesink** [nornir-automation/nornir#795]
Working with Nornir, I've noticed for some time that when I check for outdated modules (i.e., `pip list --oudated`), `typing-extensions` comes up.  But I cannot update it, as I get an error due to Nornir.  So I have to revert back.

I'm currently sitting on v3.10.0.2, even though v4.0.0 came out in Nov. 2021, and it's currently at v4.1.1.  This is due to Nornir's dependencies as shown here:

```
% pipdeptree -p nornir
nornir==3.2.0
  - mypy-extensions [required: >=0.4.1,<0.5.0, installed: 0.4.3]
  - ruamel.yaml [required: >=0.16, installed: 0.17.21]
    - ruamel.yaml.clib [required: >=0.2.6, installed: 0.2.6]
  - typing-extensions [required: >=3.7,<4.0, installed: 3.10.0.2]
```
Is there any intention of updating this?  Just curious.

(I'm also seeing that the `nornir_netmiko` plugin is bound to Netmiko < 4, but Netmiko 4.0.0 just came out a few weeks ago, so I figure that may take a bit.  And that's already been brought up in the relevant [plugin GitHub repo](https://github.com/ktbyers/nornir_netmiko/issues/32).)

**Comment by dbarrosop** [comment]
I just released 3.3.0 which should have its dependencies updated to their latest versions
