### ISSUE TITLE
nornir.plugin.runners.Threadedrunner() argument after ** must be a mapping, not str

### ISSUE THREAD

**Issue by raj15119** [nornir-automation/nornir#810]
Hello Guys, I am getting this error.

This is my code:

from nornir import InitNornir
from nornir_scrapli.tasks import send_command 
from nornir_utils.plugins.functions import print_result

nr = InitNornir(config_file="config.yaml")

results = nr.run(task=send_command, command="show version")

print_result(results)
![Capture](https://user-images.githubusercontent.com/67935401/179167022-e5c58f8c-f971-492d-bbc0-9bfbd3af14e6.PNG)

**Comment by dbarrosop** [comment]
Your config is most likely wrong, make sure it is correct.

**Comment by raj15119** [comment]
> Your config is most likely wrong, make sure it is correct.

Not sure what is wrong in config. This is output of config.yaml.

---

inventory:
    plugin: SimpleInventory
    options:
        host_file: "hosts.yaml"
        group_file: "groups.yaml"
        defaults_file: "defaults.yaml"

runner:
    plugin: threaded
    options:
        num_workers:5

**Comment by ktbyers** [comment]
@raj15119 That is wrong `num_workers:5`

You need a space between the number and the colon or else YAML will say it is a string (as opposed to a key-value pair).

**Comment by raj15119** [comment]
> @raj15119 That is wrong `num_workers:5`
> 
> You need a space between the number and the colon or else YAML will say it is a string (as opposed to a key-value pair).

Thanks 🙏 @ktbyers it was the issue...
