### ISSUE TITLE
NORNIR error

### ISSUE THREAD

**Issue by DevLabInfo** [nornir-automation/nornir#824]
when i want to connect to my devices i have an error, below  here is the traceback for the error.
some informations for my tools:
1. ubuntu 22.04
2. Nornir  3.3.0
3. python 3.10
4. SSL 3.0.2

I need your help please, i passed on a week, but i'm tired, so help please.
***********************************************************************TRACEBACK*****************************************************************
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/usr/local/lib/python3.10/dist-packages/nornir_napalm/plugins/tasks/napalm_get.py", line 32, in napalm_get
    device = task.host.get_connection(CONNECTION_NAME, task.nornir.config)
  File "/usr/local/lib/python3.10/dist-packages/nornir/core/inventory.py", line 494, in get_connection
    self.open_connection(
  File "/usr/local/lib/python3.10/dist-packages/nornir/core/inventory.py", line 546, in open_connection
    conn_obj.open(
  File "/usr/local/lib/python3.10/dist-packages/nornir_napalm/plugins/connections/__init__.py", line 57, in open
    connection.open()
  File "/usr/local/lib/python3.10/dist-packages/napalm/eos/eos.py", line 229, in open
    raise ConnectionException(str(ce))
napalm.base.exceptions.ConnectionException: Socket error during eAPI connection: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:997)
********************************************************************************************************************************************************

script_test_file:
from nornir import InitNornir
from nornir_utils.plugins.functions import print_result
from nornir_napalm.plugins.tasks import napalm_get

nr = InitNornir(
    config_file="config.yaml", dry_run=True
)

results = nr.run(
    task=napalm_get, getters=["facts"]
)
print_result(results)

#####################################################################################################

**groups.yaml :**
# groups.yaml
---

eos:
  platform: arista_eos

#########################################################################################################
**hosts.yaml :** 
# hosts.yaml
---

ceos1:
    hostname: 192.168.0.5
    platform: "eos"
    user: "admin"
    password: "admin"
    groups: 
        - eos
    
ceos2:
    hostname: 192.168.0.6
    platform: "eos"
    user: "admin"
    password: "admin"
    groups:
        - eos
    ####################################################################################################
**config.yaml :** 

# config.yaml
---
inventory:
     plugin: SimpleInventory
     options:
         host_file: 'inventory/hosts.yaml'
         group_file: 'inventory/groups.yaml'
         defaults_file: 'inventory/defaults.yaml'
runner:
     plugin: threaded
     options:
         num_workers: 2
##########################################################################################################

i'm note a prod, please help!!!!!

**Comment by ubaumann** [comment]
I think this issue is pyeapi related. Found the following note in the code:
https://github.com/arista-eosplus/pyeapi/blob/develop/pyeapi/client.py#L433

**Comment by DevLabInfo** [comment]
@ubaumann i come back to thank you, it's run now without errors.
