### ISSUE TITLE
Does support to initialize SimpleInventory with native objects still work?

### ISSUE THREAD

**Issue by kyoungwookmin** [nornir-automation/nornir#825]
Does support to initialize SimpleInventory with native objects still work?
nornir.version is 3.3.0

I'm trying various things, but I'm getting an error.

1. TypeError: SimpleInventory.init() got an unexpected keyword argument 'hosts'

from nornir import InitNornir
nr = InitNornir(inventory={
    "plugin": "SimpleInventory",
    "options": {
        "hosts": {
            "host1": {
                "username": "user",
                "groups": ["group_a"],
                "data": {"a": 1, "b": 2},
            },
        },
        "groups": {"group_a": {"platform": "linux"}},
        "defaults": {"data": {"a_default": "asd"}},
    }
})

2. PluginNotRegistered: plugin 'nornir.plugins.inventory.SimpleInventory' is not registered

from nornir import InitNornir
from nornir.plugins.inventory import SimpleInventory
from nornir.core.plugins.inventory import InventoryPluginRegister
InventoryPluginRegister.register("SimpleInventory", SimpleInventory)

nr = InitNornir(inventory={
    # "plugin": "SimpleInventory",
    "plugin": "nornir.plugins.inventory.SimpleInventory",
    "options": {
        "hosts": {
            "host1": {
                "username": "user",
                "groups": ["group_a"],
                "data": {"a": 1, "b": 2},
            },
        },
        "groups": {"group_a": {"platform": "linux"}},
        "defaults": {"data": {"a_default": "asd"}},
    }
})

**Comment by dbarrosop** [comment]
Not since 2+ years ago when nornir 3 was released. If you want to create your inventory programmatically you will either need to write your own inventory plugin or leverage some third party one. If I am not mistaken [nornir_salt](https://github.com/dmulyalin/nornir-salt) includes one you may be able to leverage.

**Comment by dbarrosop** [comment]
Closing as this is not an nornir issue.
