### ISSUE TITLE
Fallback to local credentials in case of TACACS unavailability 

### ISSUE THREAD

**Issue by mklimkow** [nornir-automation/nornir#830]
Hi,

I'm trying to build some logic for fallback to local credentials in case of TACACS unavailability. 
My idea was to use TransformFunction which is working fine with inventory transformation, but I'm unable to connect to the host that previously has failed to authenticate. Does Nornir have some kind of mechanism to omit such hosts in next connection attempts?
If so, how to bypass it?

Or maybe there is a better way to achieve my goal?

Best Regards

MK

**Comment by dbarrosop** [comment]
You have all the information here: https://nornir.readthedocs.io/en/latest/tutorial/failed_tasks.html#Skipped-hosts

**Comment by mklimkow** [comment]
Thanks, this is exactly what I was looking for.
