### ISSUE TITLE
Create a second connection

### ISSUE THREAD

**Issue by draggeta** [nornir-automation/nornir#839]
I've been reading the docs and may have missed this. I'm trying to figure out if there is a way to set up another connection with different credentials.

I'm trying to add and modify users on devices and being able to validate that the new users can connect (or modified users), would be great. However, from what I can see, a manual connection affects the existing connection.

Is there a way to temporarily connect to a device while maintaining the current connection as well?

I can seem to do it with different plugins (use napalm for one connection, netmiko for another) or just using the modules directly, but I would prefer to use the same plugin for both.

**Comment by dbarrosop** [comment]
No, what you can do is create a second host with the new credentials and use that one instead. You can add hosts dynamically to the inventory to achieve this or you could have them in your inventory.

Closing the issue as there isn't anything to do here but feel free to reopen or to keep commenting if you have further questions.
