### ISSUE TITLE
mypy_extensions is only declared as a dev dependency but it directly imported

### ISSUE THREAD

**Issue by nemith** [nornir-automation/nornir#861]
We are failing to run some CI tests as mypy_extensions is missing 

```
/usr/local/lib/python3.8/site-packages/nornir/__init__.py:3: in <module>
    from nornir.init_nornir import InitNornir
/usr/local/lib/python3.8/site-packages/nornir/init_nornir.py:3: in <module>
    from nornir.core import Nornir
/usr/local/lib/python3.8/site-packages/nornir/core/__init__.py:6: in <module>
    from nornir.core.inventory import Inventory
/usr/local/lib/python3.8/site-packages/nornir/core/inventory.py:23: in <module>
    from mypy_extensions import Arg, KwArg
E   ModuleNotFoundError: No module named 'mypy_extensions'
```

Looking at  https://github.com/nornir-automation/nornir/blob/main/pyproject.toml#L43 it is only declaring mypy_extentions as a dev dependency but in this case it is not a dev dependency but   

My guess is something else changes in our dep tree that removed mypy_extension but it needs to be explicitly declared as a runtime dependency as it is being directly imported here https://github.com/nornir-automation/nornir/blob/main/nornir/core/inventory.py#L23

**Comment by nemith** [comment]
Seems like using these are deprecated anyway. https://mypy.readthedocs.io/en/stable/additional_features.html?highlight=mypy_extensions#extended-callable-types

**Comment by ubaumann** [comment]
Nornir was just released some hours ago but we missed this line: https://github.com/nornir-automation/nornir/blob/325c8ca479b08662a0f963a90d3328a34ef17f2a/nornir/core/inventory.py#L23

I will take a look when I am home.
In the meantime you can pin the nornir version or add it to your dependencies

**Comment by ktbyers** [comment]
Fixed here:

https://github.com/nornir-automation/nornir/pull/867

New Nornir version 3.4.1 released to pypi.
