### ISSUE TITLE
Need support for reading in plural hosts.yaml in order to format the stored switch infos

### ISSUE THREAD

**Issue by Laplacence** [nornir-automation/nornir#871]
Currently I'm using an environment where the hosts.yaml file is over 10,000 lines, difficult to read and hard to maintain.

Would it be possible to add this type of support? For example, like ansible, all files in the inventory folder can be read.

**Comment by ubaumann** [comment]
There are many inventory plugings available.  Also a Ansible inventory. 

https://nornir.tech/nornir/plugins/

**Comment by Laplacence** [comment]
Thanks for the reply! I'll check the link.
