### ISSUE TITLE
Suggestion: Introduce Ruff

### ISSUE THREAD

**Issue by ogenstad** [nornir-automation/nornir#919]
Introduce [Ruff](https://docs.astral.sh/ruff/) and have it replace:

* Black
* isort
* pylama

While Ruff also has checks for type annotations the recommendation is still to keep using mypy.

Thoughts around this @dbarrosop & @ktbyers?

**Comment by dbarrosop** [comment]
I have no opinion, as long as it covers the same functionality (or even more) than the ones being replaced I am good. The formatter is the only thing that I am not sure about. Is it as extremely opinionated as black? I may not always agree with black but I like that I (or anyone else) have no choice other than to abide by it :)

**Comment by ogenstad** [comment]
Ruff will have more functionality, it's pretty much as opinionated as Black (https://docs.astral.sh/ruff/formatter/#black-compatibility), there are some slight changes depending on the codebase there could be a small number of lines that change during the migration.

I think it's nice as it's fewer tools to deal with, it's also faster though that doesn't have much of an impact on this codebase.

**Comment by ogenstad** [comment]
Fixed in #926 and #930
