### ISSUE TITLE
Module Not Found

### ISSUE THREAD

**Issue by sydasif** [nornir-automation/nornir#977]
I found this error

"(.venv) ➜  nornir_script python 01_nornir.py
Traceback (most recent call last):
  File "/home/zolo/python-lab/nornir_script/01_nornir.py", line 1, in <module>
    from nornir import InitNornir
  File "/home/zolo/python-lab/.venv/lib/python3.10/site-packages/nornir/__init__.py", line 1, in <module>
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'"

when I commented on these two lines in nornir/__init__.py it worked.

# import pkg_resources

from nornir.init_nornir import InitNornir

# __version__ = pkg_resources.get_distribution("nornir").version

__all__ = ("InitNornir", "__version__")

 

nornir version: 3.4.1
python version: 3.10 on WSL1

**Comment by ktbyers** [comment]
@sydasif Try `pip install setuptools`

Alternatively, try using the Nornir `develop` branch.

**Comment by sydasif** [comment]
@ktbyers After installing setuptools the problem has been solved. Thank you.

**Comment by ktbyers** [comment]
Should be fixed.
